### ISSUE TITLE
Notify user transaction history needs time to update

### ISSUE THREAD

**Issue by robhyrk** [zeitgeistpm/ui#1001]
there is a slight delay between purchasing an asset and it showing up on the transaction history section. There should be a notification on this page to let the user know that the transaction history may take some time to populate.

**Comment by Robiquet** [comment]
Maybe a better option would be to refactor the portfolio page to query assets from on chain. @yornaath do you remember if there were any issues with this approach?

**Comment by Robiquet** [comment]
@saboonikhil let us know that the new version of Subsquid will indexing all new blocks immediately (rather than waiting for finalisation) so that would solve this issue

**Comment by lsaether** [comment]
@saboonikhil When will the indexer follow new blocks?

**Comment by lsaether** [comment]
@saboonikhil Any updates?
