### ISSUE TITLE
Replace hovers with clicks for mobile users

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#1027]
Mobile users are unable to access certain information that is only displayed on mouse hover.

It would be good to have a generic component to handle this behaviour

**Comment by yornaath** [comment]
@Robiquet Can you outline in which places this happen? We are using some different patterns(js events, css class) to detect hovers. Tailwind hover: I thin handles click on mobile by default though.

**Comment by Robiquet** [comment]
> @Robiquet Can you outline in which places this happen? We are using some different patterns(js events, css class) to detect hovers. Tailwind hover: I thin handles click on mobile by default though.

I am not sure if we are using hover anywhere now, I can double check though
