### ISSUE TITLE
Investigate using the ws protocol in stress tests

### ISSUE THREAD

**Issue by TvrtkoM** [zeitgeistpm/ui#103]
https://www.blazemeter.com/blog/jmeter-websocket-samplers-a-practical-guide)

**Comment by usman-qa-ztg** [comment]
- I have done the investigation using the ws protocol in stress tests. 
- A detailed document and zip file of JMeter test can be found in the attachments.

**Link to the document**
https://docs.google.com/document/d/1919d0bVR_wYdLH1YkUDqBdXlyhCoYsU8UFkl-5NbgYE/edit?usp=sharing

**Jmeter file** 
[WebSocket_Test.jmx.zip](https://github.com/zeitgeistpm/ui/files/8834312/WebSocket_Test.jmx.zip)
