### ISSUE TITLE
Updated card designs

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/ui#1037]

**Comment by mk26071980** [comment]
https://www.figma.com/file/4bcQaDxzXf9qviF95bka5V/UX%2FUI_Workfile_Not4Devs?node-id=13%3A14951&t=NhGQnT5v12S6uEzp-1

**Comment by Robiquet** [comment]
We should also figure out how to display the resolved outcome, it looks a bit weird at the moment:
<img width="817" alt="image" src="https://github.com/zeitgeistpm/ui/assets/4950844/922da227-b8b5-4abd-ad45-f196bc1842d3">

**Comment by robhyrk** [comment]
@mk26071980 are the designs for this completed?

@Robiquet @mk26071980 what do you think about removing the progress bar for resolved markets and adding something like "Market Resolved to xxxx"

**Comment by Robiquet** [comment]
> @mk26071980 are the designs for this completed?
> 
> @Robiquet @mk26071980 what do you think about removing the progress bar for resolved markets and adding something like "Market Resolved to xxxx"

Yeah I think something like that makes sense

**Comment by lsaether** [comment]
@mk26071980 please link card designs
