### ISSUE TITLE
Add liquidity section dropdown instead of tabs

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/ui#1039]

**Comment by mk26071980** [comment]
https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?node-id=3970%3A22391&t=V9GiGyfuf4aBvLkF-1

**Comment by Robiquet** [comment]
@mk26071980 could you share the Buy/Sell full set modal too? It's needed to complete this as there is only 1 one button for it
