### ISSUE TITLE
Rework portfolio page

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/ui#1041]

**Comment by mk26071980** [comment]
April 19th, 2023 Version
https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?node-id=3970%3A22392&t=39sakXJxIhW0ruJr-1

**Comment by Robiquet** [comment]
Might need a little rework as we are displaying more information:


![Image](https://github.com/zeitgeistpm/ui/assets/4950844/a1978275-d540-475d-a293-60129b88b803)



![Image](https://github.com/zeitgeistpm/ui/assets/4950844/164ca861-d391-4e8f-b869-841e5246731f)



![Image](https://github.com/zeitgeistpm/ui/assets/4950844/8b50cb10-2a5f-43b2-84ba-d01ef538cb12)
