### ISSUE TITLE
Grace period bug

### ISSUE THREAD

**Issue by Boibit** [zeitgeistpm/ui#1043]
Preset grace period buttons are not assigning proper time/date.

![image](https://user-images.githubusercontent.com/61936910/232078289-0ee7d9d0-0bca-4497-b6e7-4742ac5a7d64.png)
![image](https://user-images.githubusercontent.com/61936910/232078102-883c22af-04b1-4313-9622-157e0a00fc52.png)

**Comment by lsaether** [comment]
Included in the create market page redesign
