### ISSUE TITLE
Price history displays conflicting information depending on display range

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#1105]
Here are the day/week/month histories of market 21, taken April 24, 11:30 UTC. Looking at the two favorites, you'll see that each history shows a different development. That's confusing.

<img width="1234" alt="Screenshot 2023-04-24 at 13 28 33" src="https://user-images.githubusercontent.com/49552287/233985057-60cdc552-185c-4488-a829-20c3a908cdf4.png">
<img width="1226" alt="Screenshot 2023-04-24 at 13 28 10" src="https://user-images.githubusercontent.com/49552287/233985072-641d01a0-641a-4966-b188-1b36f076505f.png">
<img width="1195" alt="Screenshot 2023-04-24 at 13 27 47" src="https://user-images.githubusercontent.com/49552287/233985076-1c29fabc-80ad-47e7-ab2b-39c9c3df2409.png">

**Comment by Robiquet** [comment]
We can show a more granular price history to help combat this though there is quite a bit of a performance hit. @saboonikhil are there any further optimisations that you can do?

**Comment by Robiquet** [comment]
> Why is the startTime changing? I guess `Day`, `Week` and `Month` account for interval types keeping startTime & endTime constant.

This is to select the time between now and the startTime 
<img width="172" alt="image" src="https://user-images.githubusercontent.com/4950844/233992834-dc0d7625-6a8b-469e-b0e1-78e3f28c7f12.png">

**Comment by saboonikhil** [comment]
Eyeing on subsquid's new version and some query optimisations to allow room for granular level querying.
