### ISSUE TITLE
Error on liquidity page: cannot read properties of null (reading '0')

### ISSUE THREAD

**Issue by robhyrk** [zeitgeistpm/ui#1135]
In `PoolTable` component `line 69`: `category = market?.categories[index];` shows error: `Cannot read properties of null (reading '0')`

This happens on `liquidity/7`

**Comment by TvrtkoM** [comment]
it is pool of destroyed market and it shouldn't happen on production deployment. Created a new issue for refactoring liquidity page that should fix this issue - #1170
