### ISSUE TITLE
Scalar market range not showing current prediction on market page.

### ISSUE THREAD

**Issue by Boibit** [zeitgeistpm/ui#1154]
Market was deployed with initial prediction for '600'. This initial prediction is reflected in the market card, but is not showing properly on the market page itself. https://app.zeitgeist.pm/markets/145
![image](https://user-images.githubusercontent.com/61936910/236264355-24cbff61-5d44-47fe-9419-c5d083340357.png)

**Comment by robhyrk** [comment]
This issue seems to be resolved now. There were some changes being done on the this page at the time and some code may be have been removed accidentally.

**Comment by lsaether** [comment]
Closing as this is reported to be resolved. @Boibit please re-open if it becomes an issue again.
