### ISSUE TITLE
Price history diagram is updated slowly

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#1196]
Not sure if this is related to #1105. The price history diagram is not _immediately_ updated after making a trade. I believe that's a problem for two reasons:

1. Conflicting information between the two price indicators.
<img width="1920" alt="Screenshot 2023-05-12 at 00 08 59" src="https://github.com/zeitgeistpm/ui/assets/49552287/d208c727-c790-4799-93e7-67f5db3823e5">

2. User doesn't immediately see their impact in the graphics.

**Comment by Robiquet** [comment]
We can make it faster but it won't be immediate due to subsquid limitations. These should be resolved soon with unfinalised block indexing
