### ISSUE TITLE
Allow pool weights to be configurable 

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#126]
We should allow pool weights to be configurable to allow liquidity providers to adjust the initial positioning in the market. 

I believe there are many assumptions in the code base that assume equal weightings for pool assets. These need to be reviewed

**Comment by mk26071980** [comment]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/80706590/177278990-ef21bd7c-6c53-4e30-ae33-187d1dabd240.png">

https://www.figma.com/proto/qe6BhxbYH06MXOf1Lkuv9i/App_v1.00.01?page-id=12%3A2054&node-id=328%3A2188&viewport=4387%2C760%2C0.5&scaling=min-zoom&starting-point-node-id=247%3A3722&show-proto-sidebar=1
