### ISSUE TITLE
Inconsistent use of comma/decimal point in trading slip

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#1261]
Sometimes it's a comma, sometimes it's a decimal point. Please disregard the mark around _Trading Fee_.

<img width="455" alt="Screenshot 2023-05-24 at 12 59 38" src="https://github.com/zeitgeistpm/ui/assets/49552287/4f3b027f-e95f-44f1-be0c-79b35f935e7e">

**Comment by Robiquet** [comment]
What is your preference for separators? Should it be based on locale or hardcoded to US ones?

**Comment by maltekliemann** [comment]
Looking at popular trading sites, they all seem to use hardcoded US separators. In some CEXs, I can change my timzone, but can't change the separator style in any of them. Uniswap auto-converts a comma into a decimal point. So I'd say go with hardcoded US separators.

**Comment by Robiquet** [comment]
We should switch to all "US" separators
