### ISSUE TITLE
Market history should be shown when market is closed

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#1305]
So users can see what was reported
<img width="1155" alt="image" src="https://github.com/zeitgeistpm/ui/assets/4950844/dd42f6db-b7ae-47f6-8f95-939df64fee23">

**Comment by robhyrk** [comment]
@Robiquet was the market reported just shortly around when you noticed this? The market now has the history. It's setup to show when markets are reported, disputed, or resolved so I wonder if there just a delay between when the data was indexed?

**Comment by Robiquet** [comment]
> @Robiquet was the market reported just shortly around when you noticed this? The market now has the history. It's setup to show when markets are reported, disputed, or resolved so I wonder if there just a delay between when the data was indexed?

Yeah looks like it was reported fairly recently, so perhaps that is the issue
