### ISSUE TITLE
Market list filtering shows different markets even when the url query is the same

### ISSUE THREAD

**Issue by yornaath** [zeitgeistpm/ui#132]
How to reproduce.

1. Go to markets list.
2. Click clear all.
3. Click clear all again.
4. Observe list items change even though database shouldnt have changed.

_Edit, some filters also appear to not work completely. And even though the list loaded for a set of filters, when refreshing it shows no results._

**The bug seems to stem from the sdk:**
Related issue: zeitgeistpm/tools#202

**Comment by TvrtkoM** [comment]
there was an issue with our indexer that caused this
