### ISSUE TITLE
Teleporting all DOT from Polkadot to Zeitgeist fails

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#1347]
If I have 150 DOT on Polakdot and want to transfer it all to Zeitgeist, the form lets me specify 150 DOT to transfer. But that's too much because I also have to pay for the fees of the transfer. So when we install a MAX button, the button has to take fees into account.

Also, there's no error message when the transfer fails.

**Comment by lsaether** [comment]
Might be fixed. @Robiquet will test it
