### ISSUE TITLE
Get DOT / integrate banxa

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#1364]
UX flow:
1. Buy DOT from non-custodial exchange 
2. Listen for DOT address changes
3. When balance arrives display button to move full balance to Zeitgeist
4. Direct user to active DOT markets

Non-custodial exchange options
Banxa ("Polkadot native")
<img width="522" alt="image" src="https://github.com/zeitgeistpm/ui/assets/4950844/454e3cf3-af15-4fc5-a6d0-e7433480de16">
Moonpay (Used by Uniswap, worse prices)
<img width="480" alt="image" src="https://github.com/zeitgeistpm/ui/assets/4950844/65f61bf4-8ce4-4871-b0f0-5986148876f2">
Ramp (Best prices)
<img width="407" alt="image" src="https://github.com/zeitgeistpm/ui/assets/4950844/82963ad4-78c2-44b9-bb5b-ededd5f61b0e">

**Comment by lsaether** [comment]
Another option: https://onramp.money/

**Comment by lsaether** [comment]
Another option is Sygma
