### ISSUE TITLE
Regenerate market page SSR every 1 minute

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#1381]
The only way I can tell what outcome was reported is by checking which _Report Outcome_ button is greyed out. Seems unintuitive and might throw people off.

<img width="1920" alt="Screenshot 2023-06-19 at 10 34 51" src="https://github.com/zeitgeistpm/ui/assets/49552287/f511da47-28b4-42f9-86fe-83eb1a6bde90">

<img width="1920" alt="Screenshot 2023-06-19 at 10 35 05" src="https://github.com/zeitgeistpm/ui/assets/49552287/e00c24cf-399d-46fa-9d51-01a8b21543ec">

**Comment by lsaether** [comment]
Should be solved with the new status boxes on the market page @mk26071980
