### ISSUE TITLE
Withdraw liquidity modal of resolved DOT market shows only DOT as withdrawable asset

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#1382]
This should actually show the winning token as well.

<img width="1920" alt="Screenshot 2023-06-19 at 10 38 58" src="https://github.com/zeitgeistpm/ui/assets/49552287/c7cb0981-7ce4-4329-919a-3cdf95d1031c">

**Comment by lsaether** [comment]
@maltekliemann Are you able to withdraw liquidity?

**Comment by maltekliemann** [comment]
Sorry for the late reply. This doesnt' appear to be solved with _resolved_ markets (see market 176 on mainnet). I'm guessing this is related to the removal of the assets from the pool?
