### ISSUE TITLE
Ticker generation gives strange results on one-word outcomes

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#1408]
Should probably not use the first and the last word if there's only one word.

<img width="1569" alt="Screenshot 2023-06-21 at 10 37 05" src="https://github.com/zeitgeistpm/ui/assets/49552287/4df14940-fa0a-41b3-bc4e-1c07d5f7e6c4">

**Comment by Robiquet** [comment]
Think we should get rid of the tickers on the create page. They are not used anywhere else in the app

**Comment by lsaether** [comment]
Make the outcome text smaller on the tables in liquidity section - doesn't need design work @Robiquet

**Comment by yornaath** [comment]
I have improved(hopefully) this in a now merged pr that will be on prod soon.
@mk26071980 Can you test here: https://staging.zeitgeist.pm/create and see if the tickers make more sense to you given our outcomes?

**Comment by lsaether** [comment]
Reopen if there's an issue.

**Comment by maltekliemann** [comment]
Already done, only discovered this problem: https://github.com/zeitgeistpm/ui/issues/1588
