### ISSUE TITLE
Show grace period for markets

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#1440]
It's impossible to see what the grace period of a market is. This is frustrating for advisors who have to resort to polkadot-js if they want to know if the grace period is correct. I suggest the following:

<img width="1920" alt="Screenshot 2023-06-26 at 10 30 31" src="https://github.com/zeitgeistpm/ui/assets/49552287/32645949-fbeb-49f3-870d-53899421cf4d">

I think maybe the user shouldn't be bothered too much with the specifics of the grace period. Instead using "Reported: (Market close) + (Grace period)" seems easier to understand. If "Reported" is too unclear, use "Open to Reports". Or something like that.

**Edit.** Replace "Resolves" with "Reported".

**Comment by maltekliemann** [comment]
It also wouldn't hurt users to see what the dispute period is. If the period is 1 hour but users expected 4 days, they might get upset.

**Comment by Robiquet** [comment]
@maltekliemann wouldn't the "resolves" value be closer to grace period + reporting period + dispute period?
