### ISSUE TITLE
Header shouldn't cover banner

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#1448]
<img width="1439" alt="image" src="https://github.com/zeitgeistpm/ui/assets/4950844/0a80a9a0-263d-4a76-ad0f-b5f4936aa8bf">
The banner should sit lower down the page or header should fade in on scroll as it did previously

**Comment by mk26071980** [comment]
![Image](https://github.com/zeitgeistpm/ui/assets/80706590/fc331609-00b9-41e8-8faa-2863034098c7)

https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?type=design&node-id=3959%3A22426&mode=design&t=pv8l5ecpZR5wMHGf-1

**Comment by Robiquet** [comment]
adding some margin to the top of the banner for now
