### ISSUE TITLE
Scrolling changes values in "Deploy Market" view

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#1481]
If you hover over the price of an asset and then scroll up or down, the value is incremented/decremented. We don't want this. Note that this makes it possible to set the price to negative values.

<img width="1920" alt="Screenshot 2023-07-03 at 14 01 30" src="https://github.com/zeitgeistpm/ui/assets/49552287/f71239d3-5eb3-4ce2-84ab-3f080d9b4a81">

**Comment by lsaether** [comment]
- Disable standard scroll behavior
- Create single input component that can be re-used throughout the app
