### ISSUE TITLE
Settings - in case of faulty rpc url app still tries to connect after reverting

### ISSUE THREAD

**Issue by TvrtkoM** [zeitgeistpm/ui#150]
After a number of tries the app will revert to last known configuration that worked or will connect to the testnet. After the revert happened, cnsole still prints  errors for the faulty url e.g. 

```
logger.js?767c:81 2022-07-25 15:51:51          API-WS: DOMException: Failed to construct 'WebSocket': The URL 'ws://127.0.0.1:99444' is invalid.
    at WsProvider.connect (webpack-internal:///./node_modules/@polkadot/rpc-provider/cjs/ws/index.js:509:204)
    at WsProvider.connectWithRetry (webpack-internal:///./node_modules/@polkadot/rpc-provider/cjs/ws/index.js:543:20)
    at eval (webpack-internal:///./node_modules/@polkadot/rpc-provider/cjs/ws/index.js:546:16)

```

**Comment by yornaath** [comment]
The console ended up being flooded with connection retry errors because the timeout abandoned the connection and didn't disconnect the provider. I have provided a fix in the following pr on the sdk: zeitgeistpm/tools#212

**Comment by Robiquet** [comment]
If we want to limit retries I think we will still need some changes to the app too

**Comment by yornaath** [comment]
> If we want to limit retries I think we will still need some changes to the app too

Not really with the approach I am taking here. It retries within the timeout window 15sec, it fails if it either cannot connect within that time window or has more than five failed connection attempts.

**Comment by Robiquet** [comment]
Are you sure? To me it looks like we'll still have an infinite loop here if `initSDK` throws and error https://github.com/zeitgeistpm/ui/blob/8653f421828b4bbc2a9d870f4e65617932ca323c/lib/stores/Store.ts#L179

**Comment by yornaath** [comment]
> Are you sure? To me it looks like we'll still have an infinite loop here if `initSDK` throws and error
> 
> https://github.com/zeitgeistpm/ui/blob/8653f421828b4bbc2a9d870f4e65617932ca323c/lib/stores/Store.ts#L179

I am not experiencing that in the app, wont `setNextBestEndpoints` try another one when it fails? So it will only be a infinite loop until one of the endpoints can connect.

**Comment by Robiquet** [comment]
But what if the next best endpoint fails too? I think the current behaviour is ok for now, just pointing out that we still have a infinite loop if all possible endpoints are down
