### ISSUE TITLE
Styling adjustments

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#152]
Apply styling adjustments as described here:
https://www.figma.com/file/OeZDleqPEMARMgHpjWQvtd/Styling_Comments?node-id=4%3A14

- [x] #206
- [ ] #207
- [ ] #208
- [x] #209
- [x] #210
- [x] #211
- [ ] #212
- [ ] #213

**Comment by lsaether** [comment]
closing this in favor of opening issues with specific changes that need to be made and can be more easily tracked
