### ISSUE TITLE
Zero balance sometimes prefixed with a minus

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#1542]
Technically correct, but certainly not pretty:

<img width="1920" alt="Screenshot 2023-07-11 at 15 02 11" src="https://github.com/zeitgeistpm/ui/assets/49552287/69f68687-0a3d-4be7-b570-bf63271479c6">

**Comment by yornaath** [comment]
I found that this was market 130, and in production it does show prefixed with minus, but when running the current working(staging) branch it shows without the prefix. Not sure if this is indirectly fixed in dev, or if some config or static generation in prod affects it. Thoughts @Robiquet ?

**Comment by Robiquet** [comment]
> I found that this was market 130, and in production it does show prefixed with minus, but when running the current working(staging) branch it shows without the prefix. Not sure if this is indirectly fixed in dev, or if some config or static generation in prod affects it. Thoughts @Robiquet ?

Hmm I'm seeing it on both
https://staging.zeitgeist.pm/markets/130
https://app.zeitgeist.pm/markets/130

**Comment by yornaath** [comment]
Yeah I just tried to `yarn build:prod`(added the command) and `yarn start` locally and it is indeed prefixed, so I think its related to static generation

**Comment by Robiquet** [comment]
@yornaath Liquidity is fetched client side though

**Comment by yornaath** [comment]
Yeah just seeing that, will do some debugging
