### ISSUE TITLE
Error message for insufficient liquidity shows wrong base asset

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#1553]
Says ZTG, but should be DOT. Also, this still seems to take `MinLiquidity` into account, which was removed in the last update.

<img width="843" alt="Screenshot 2023-07-13 at 20 44 01" src="https://github.com/zeitgeistpm/ui/assets/49552287/e57d1d8f-02b5-4153-915e-6e2daf207f7e">

**Comment by TvrtkoM** [comment]
Can't reporduce this @maltekliemann . 

![Image](https://github.com/zeitgeistpm/ui/assets/551965/9a61111b-3a98-4c08-af08-7383dd84db86)

**Comment by maltekliemann** [comment]
Yeah, seems like this is fixed already.
