### ISSUE TITLE
Add thousands separator to scalar values

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#1572]
So "5,000,000" instead of 5000000. Too difficult to read this otherwise.

<img width="1920" alt="Screenshot 2023-07-18 at 20 07 34" src="https://github.com/zeitgeistpm/ui/assets/49552287/352e6e61-c47a-4711-ae03-fee69233d237">

<img width="1920" alt="Screenshot 2023-07-18 at 20 08 34" src="https://github.com/zeitgeistpm/ui/assets/49552287/e26502f2-688a-4149-ac09-c06ff06e33c5">

**Comment by Robiquet** [comment]
@maltekliemann what do you think about using compact notation is ok? For example "110K", "30.3M", etc?
