### ISSUE TITLE
Main page new layout for banner and News section

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/ui#1607]
Replace the carousel with the main banner and news section that links out to blog posts.

**Comment by Robiquet** [comment]
@mk26071980 do we have a mobile design for this?

**Comment by lsaether** [comment]
@mk26071980 Can you link the designs?

**Comment by mk26071980** [comment]
https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?type=design&node-id=7448%3A5696&mode=design&t=aKobFPqRacvTD0w9-1

**Comment by yornaath** [comment]
Pull request #1737 should cover the new front page design entirely I think. Only thing left is the link for the learn more button and the video. Should the video be displayed on page or be a link? @lsaether
