### ISSUE TITLE
New market page

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/ui#1610]

**Comment by lsaether** [comment]
@mk26071980 Need to make a mobile design

**Comment by lsaether** [comment]
Can work on the desktop page, and mobile designs will come soon

**Comment by Robiquet** [comment]
Could you provide the design to show what the buy and sell buttons do on smaller screens

**Comment by lsaether** [comment]
@mk26071980 Can you link to designs?

**Comment by mk26071980** [comment]
https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?type=design&node-id=6790%3A482&mode=design&t=aKobFPqRacvTD0w9-1

**Comment by Robiquet** [comment]
https://github.com/zeitgeistpm/ui/issues/1749
