### ISSUE TITLE
New leaderboard design

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/ui#1614]

**Comment by yornaath** [comment]
On issues like this its hard to tell if its meant to integrate new designs, or if its work for @mk26071980 to make/finish the designs. Could we assing Mikhail to tasks like this if its for him? Or make it clear if its design or implementation work somehow?

**Comment by yornaath** [comment]
Oh yeah we do that, its just unclear with this one since no design is linked

**Comment by lsaether** [comment]
@mk26071980 Can you link to the designs?

**Comment by mk26071980** [comment]
https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?type=design&node-id=6790%3A482&mode=design&t=aKobFPqRacvTD0w9-1
