### ISSUE TITLE
Can't see base asset in market view of proposed market

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#1642]
Not sure if I'm missing something, but if I want to ensure that the market has the right base asset before approving it, I have to use polkadot-js instead.

**Comment by Robiquet** [comment]
I guess we are not rendering this bit when a market is proposed? Maybe we could just have Liquidity: 0 "baseAsset"
<img width="297" alt="image" src="https://github.com/zeitgeistpm/ui/assets/4950844/f3506c23-d9d1-4c6a-bff2-cc94c23f95ef">

**Comment by maltekliemann** [comment]
Yeah, that part is grayed out. Seems like a solution to me.
