### ISSUE TITLE
Can't see initial price in market overview before deploying

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#1644]
I'm less interested in what the weights are, for example (they're basically an implementation detail), but I can't find what the actual prices are.

<img width="1370" alt="Screenshot 2023-08-02 at 18 46 59" src="https://github.com/zeitgeistpm/ui/assets/49552287/2fd5f3e6-748b-42ca-b0b5-c4384e33f8f7">

**Comment by Robiquet** [comment]
Looks like oracle text encoding is weird too

**Comment by maltekliemann** [comment]
x is printing weirdly. Honestly... I always thought that was a conscious stylistic choice.
