### ISSUE TITLE
Make clearing out resolved markets easier

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#1668]
Let's say I'm a big-shot LP and I provide liquidity to a couple of markets. Would be nice to have an easier time withdrawing my liquidity and redeeming the winner. I don't have a super clear idea how this can be done.

Right now, my workflow is to find the market (either in the market list or in the my portfolio), then withdraw liquidity and then use the button for redeeming.

First of all, it might be useful to have a simple overview of which markets that I'm involved in are resolved. Maybe add the market status to the markets in the portfolio (or at least add a little icon if they're resolved).

Secondly, maybe we can withdraw and redeem in one step because that's 100% what everybody is going to do anyways.
<img width="1920" alt="Screenshot 2023-08-07 at 17 20 50" src="https://github.com/zeitgeistpm/ui/assets/49552287/7a42e206-41bd-4fa4-9f9b-8a3a1eae27ba">

**Comment by Robiquet** [comment]
Can add a "Redeem Pool" button to batch exit_pool and redeem
