### ISSUE TITLE
Add comment section

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#1686]
It would be really helpful to have a comment section which can be used by users to publicly ask questions about the market or just banter. Not sure if this idea was already shut down earlier for some reason. All the other PM platforms seem to have this, so I think we should too.

**Comment by Robiquet** [comment]
Closing this in favour of https://github.com/zeitgeistpm/ui/issues/715. We already have a chat feature but it doesn't get much usage so I don't think a comment section is going to see much usage either at this stage
