### ISSUE TITLE
Adjust page background color across pages

### ISSUE THREAD

**Issue by TvrtkoM** [zeitgeistpm/ui#1711]
Acc. to designs different pages use different background colors e.g. background color of:

- leaderboard page is #D8E1E7
- market and portfolio pages is white
- markets list is #F1F1F1
- index page is #F5F5F5
- create account page is #FAFAFA
- deposit page is #FAFAFA

**Comment by mk26071980** [comment]
Done. Grey bgr is #F5F5F5
