### ISSUE TITLE
All report boxes greyed out when trying to report using proxy

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#1754]
The account has proxy access to the oracle account and then "Report Outcome" buttons are visible, but they can't be clicked.

![image](https://github.com/zeitgeistpm/ui/assets/49552287/da7c8148-5711-441e-abce-64170d0fbd72)

**Comment by robhyrk** [comment]
Tested this today on Battery Station and can confirm that proxy accounts can report outcomes. This issue was likely addressed during UI updates.
