### ISSUE TITLE
Watch How video

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#1770]
Need to record watch how video when staging it ready and add the link/embed

**Comment by yornaath** [comment]
@lsaether Can you take a look at the app in staging how it is now(https://staging.zeitgeist.pm/) with updated market page and front page, and let us know if the designs are good enough to make a "Watch How" introduction and tutorial app off of?

**Comment by yornaath** [comment]
@JamesPrestonZA How is this coming?

**Comment by Robiquet** [comment]
add this link https://www.youtube.com/playlist?list=PLdOlgpqyU8RP-ZK2A2qbcfxOlzoeuR6sx
