### ISSUE TITLE
Spacing issues on deposit and create account page

### ISSUE THREAD

**Issue by robhyrk** [zeitgeistpm/ui#1771]
![Screenshot 2023-09-05 at 5 34 37 PM](https://github.com/zeitgeistpm/ui/assets/14626415/4acef636-bff7-42dd-8d57-61d19ddeb281)

**Comment by robhyrk** [comment]
![Screenshot 2023-09-05 at 5 38 16 PM](https://github.com/zeitgeistpm/ui/assets/14626415/13558672-3840-4542-9392-e576f4f92c02)

**Comment by Robiquet** [comment]
Need to show different wallet option for mobile
