### ISSUE TITLE
Add disclaimer

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#1822]
If vpn user is detected, show disclaimer

**Comment by Boibit** [comment]
update:
Email from lawyer:
![image](https://github.com/zeitgeistpm/ui/assets/61936910/8d0a6513-719e-4fd1-8a0b-a594d2ee1903)

It seems that our general ToS already covers everything we need. They just need to be "affirmatively agreed" by users. Current questions seems to be if this will be every user, upon connecting wallets, or upon detecting vpn use.

**Comment by Robiquet** [comment]
Disclaimer should be shown to all users before signing up/ connecting wallet for the first time
