### ISSUE TITLE
Activate pre-launch countdown page

### ISSUE THREAD

**Issue by yornaath** [zeitgeistpm/ui#184]
To activate the pre launch countdown do the following in order:

- [ ] Configure the correct domain, probably `app.zeitgeist.pm` to the app. @lsaether 
- [ ] Update the `const launchDate = new Date("2022-08-22");` in `_app.tsx` to the exact launch date. 
**Blocked as we do not know the exact date yet.**
- [ ] Merge staging branch into main
- [ ] Set `NEXT_PUBLIC_PRE_LAUNCH_PHASE` in vercel env to `true`. _Remember to set it for production, preview and dev envs._
- [ ] Redeploy

**Comment by Nathanpmyoung** [comment]
This is done, right?
