### ISSUE TITLE
Dispute bond description is incorrect

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#1840]
This should depend on which dispute mechanism is used. There's only one dispute round when the mechanism is authorized. @Chralt98 knows more about how bonds increase if the mechanism is court.

<img width="1920" alt="Screenshot 2023-10-03 at 00 01 12" src="https://github.com/zeitgeistpm/ui/assets/49552287/9acb7633-41a2-44b9-a1e7-c36240246da3">

**Comment by Robiquet** [comment]
Fix will be released with next runtime release
