### ISSUE TITLE
Redeem Pool button specifies wrong limits

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#1865]
This transaction was put together by Redeem Pool: https://zeitgeist.subscan.io/extrinsic/3988354-3

The user owns 100,000,000,000 pool shares and the pool account has the following balances:

- 1,798,612,897,081 of `CategoricalOutcome(243, 0)`
- 733,036,072,729 of `CategoricalOutcome(243, 1)`
- 1,041,571,578,313 of `Ztg`

The transaction specified the limits `[1780448705433, 1031052746943]`. But the market resolved to `CategoricalOutcome(243, 1)`, which means the first limit is violated. The transaction was apparently put together assuming that the winning outcome was `CategoricalOutcome(243, 0)`.

**Comment by Robiquet** [comment]
Should be fix with https://github.com/zeitgeistpm/ui/pull/1818
