### ISSUE TITLE
Proposed market not shown on app

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#1885]
Can't see this market https://staging.zeitgeist.pm/markets/263 on the overview: https://staging.zeitgeist.pm/markets?status=Proposed&ordering=Newest&liquidityOnly=false

**Comment by Robiquet** [comment]
@saboonikhil was the indexer syncing here?

**Comment by Robiquet** [comment]
Actually there is a bug on the query, once the markets have liquidity they will shown up. I'll fix in the mean time
