### ISSUE TITLE
Image preview generation

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#1889]
Might not be working currently. Could be something to do with markets no longer having images
![image](https://github.com/zeitgeistpm/ui/assets/4950844/0e27b462-4f77-47d0-bd57-b0c313e308cf)

**Comment by yornaath** [comment]
Ah yeah probably. Should use the category/tag images prob

**Comment by Robiquet** [comment]
> Ah yeah probably. Should use the category/tag images prob

I think we have error handling on the image fetching, but maybe it's timing out. We can probably remove the image fetching entirely now
