### ISSUE TITLE
Inactive markets show skeleton on market data

### ISSUE THREAD

**Issue by robhyrk** [zeitgeistpm/ui#1891]
Should display 0 or be hidden

![Screenshot 2023-10-13 at 8 10 48 PM](https://github.com/zeitgeistpm/ui/assets/14626415/d4696f3d-3415-440b-8e44-4ce6e30d43e3)

**Comment by Robiquet** [comment]
Seems to be working now 

![Image](https://github.com/zeitgeistpm/ui/assets/4950844/4b15a0e7-01a8-49c8-8ec9-67ea8664ebf4)
