### ISSUE TITLE
Nova wallet support.

### ISSUE THREAD

**Issue by Boibit** [zeitgeistpm/ui#1901]
Nova wallet is the best mobile friendly Polkadot wallet. This would enable more mobile use of the app.

**Comment by Robiquet** [comment]
We have this already, is it not working for you?

**Comment by Boibit** [comment]
![image](https://github.com/zeitgeistpm/ui/assets/61936910/aa77e80c-adf9-4428-9dac-7aef5da0c037)

I can't actually test on my phone.
