### ISSUE TITLE
(Leaderboard) Remove Zeitgeist official accounts

### ISSUE THREAD

**Issue by Boibit** [zeitgeistpm/ui#1907]
Currently Zeitgeist controlled wallets hold the top 2 spots on the leaderboard. We should remove this so that users can take those slots.

**Comment by Robiquet** [comment]
I don't think either of these are Zeitgeist controlled wallets so I think they should stay. They look like the early arbitrage wallets and they already starting to drop off on the yearly leaderboard. Hopefully soon we will see users with greater than $300 all time profits soon
