### ISSUE TITLE
It's unclear if the time zone applies to the grace period as well

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#1930]
Judging from the design, I'd say it doesn't.

<img width="876" alt="Screenshot 2023-10-20 at 18 15 57" src="https://github.com/zeitgeistpm/ui/assets/49552287/9008b586-6d79-49b9-8993-4ebe72839dbe">

**Comment by Robiquet** [comment]
@maltekliemann I think grace period will be using local timezone which is confusing, what would your ideal solution be?

**Comment by maltekliemann** [comment]
The time zone selection should definitely apply to both. I think the design hot fix here is to place the time zone picker on its own line (or some other place special). Long term, I'd be interested if it's possible to add the time zone picker to the date picker.

I can't think of a better design right now though. I'm not sure if the grace period is going to be around for much longer, so maybe just changing the position of the time zone pciker is enough for now.

**Comment by Robiquet** [comment]
@maltekliemann What do you think about removing "Grace Period" from the create market page?

**Comment by maltekliemann** [comment]
Yeah, let's get rid of it.
