### ISSUE TITLE
Strange UI object in proposed market

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#1931]
What is this bar with 100% at the end?

<img width="1920" alt="Screenshot 2023-10-20 at 18 20 42" src="https://github.com/zeitgeistpm/ui/assets/49552287/8f993ab4-043b-426e-8e48-56bc40ca6311">

**Comment by Robiquet** [comment]
We should hide this:

![Image](https://github.com/zeitgeistpm/ui/assets/4950844/58c1b505-a3de-4681-9b69-a1bba296b264)
