### ISSUE TITLE
Account selection isn't clear

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#1997]
Users have found it hard to figure out how to switch wallets. I think we need to make it clearer that this element is a drop down
![image](https://github.com/zeitgeistpm/ui/assets/4950844/8bb441e0-dd37-4114-b7b1-9c44d74253ef)

**Comment by robhyrk** [comment]
What do you think about also consolidating the wallets and account selection modal into one? Less modal switching that way and the user can see it all in one place
