### ISSUE TITLE
Input should be disabled if user has no balance for Sell

### ISSUE THREAD

**Issue by robhyrk** [zeitgeistpm/ui#2011]
The slider is disabled but the user is able to input an amount to sell which then also causes the slider to move 

![Screenshot 2023-11-26 at 9 44 17 PM](https://github.com/zeitgeistpm/ui/assets/14626415/9760a675-ad9e-4bf7-bf9c-a0aee3708ad7)

**Comment by Robiquet** [comment]
Stop slider from moving
