### ISSUE TITLE
[Court] No way back from court case

### ISSUE THREAD

**Issue by sea212** [zeitgeistpm/ui#2030]
When viewing a specific court case, there is no button the page to get back to the Court overview. I think it makes sense to provide a button at every Court page to always get back to the root of all court pages, the overview.

**Comment by yornaath** [comment]
<img width="1277" alt="Screenshot 2023-12-11 at 12 25 03" src="https://github.com/zeitgeistpm/ui/assets/411755/6441ffea-81b7-4cf0-9664-32d362b1702c">
Does this suffice?
