### ISSUE TITLE
[Court] Show court cases where my juror account is assigned

### ISSUE THREAD

**Issue by sea212** [zeitgeistpm/ui#2031]
Currently only all court cases are shown. As a juror, I would appreciate a condensed view where I see only court cases that my juror account is assigned to.

**Comment by yornaath** [comment]
<img width="1436" alt="Screenshot 2023-12-11 at 12 15 19" src="https://github.com/zeitgeistpm/ui/assets/411755/47223039-bbe7-4f35-88be-b855190c62a3">

This should be handled. Cases where you need to take action will allways be shown on top of the list with a corresponding contextual button(vote, reveal etc)

**Comment by sea212** [comment]
I think this is fine for now. Jurors most likely check the court cases regularly.
It does not provide the information that a juror is assigned and has to act in a couple of days, which might be useful for organizing oneself, but I don't see it as necessary. Maybe this information can be provided by https://github.com/zeitgeistpm/ui/issues/2032

**Comment by sea212** [comment]
I think this is fine for now. Jurors most likely check the court cases regularly.
It does not provide the information that a juror is assigned and has to act in a couple of days, which might be useful for organizing oneself, but I don't see it as necessary. Maybe this information can be provided by https://github.com/zeitgeistpm/ui/issues/2032

**Comment by sea212** [comment]
I think this is fine for now. Jurors most likely check the court cases regularly.
It does not provide the information that a juror is assigned and has to act in a couple of days, which might be useful for organizing oneself, but I don't see it as necessary. Maybe this information can be provided by https://github.com/zeitgeistpm/ui/issues/2032
