### ISSUE TITLE
[Court] Show total slashable stake per court case

### ISSUE THREAD

**Issue by sea212** [zeitgeistpm/ui#2033]
As a viewer, I might be interested in seeing how much total slashable stake is assigned per court case. This is mostly informational, but maybe also relevant for users who `appeal` court cases.

**Comment by yornaath** [comment]
@Chralt98 How do I derive this value?

**Comment by Chralt98** [comment]
https://docs.zeitgeist.pm/docs/learn/court#calculating-necessary-draw-weights

**Comment by yornaath** [comment]
Should this be shown on the case page at all times or is it only relevant when appealing?

**Comment by yornaath** [comment]
<img width="1048" alt="Screenshot 2023-12-14 at 11 44 30" src="https://github.com/zeitgeistpm/ui/assets/411755/4ea10696-5fea-44eb-8fa9-531111d64bbf">
Is this fine?
