### ISSUE TITLE
Hide permissionless markets by default 

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#205]
Permissionless markets should be hidden by default. There should be a setting to enable them in the settings page

**Comment by mk26071980** [comment]
https://www.figma.com/file/UBJxc5KRoCRLZuS1Zqa0Kx/Sprints?node-id=0%3A1

<img width="912" alt="image" src="https://user-images.githubusercontent.com/80706590/194905124-faeab03b-054a-4cff-b8cf-2d095956efbf.png">

**Comment by Robiquet** [comment]
@lsaether do we still want to do this?
