### ISSUE TITLE
[Court] Delegation modal allows to select to delegator

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#2052]
This results in me being able to sign a transaction that we know ahead of time will fail.

**Comment by yornaath** [comment]
Dont understand this isse

**Comment by maltekliemann** [comment]
Sorry, my bad. It was supposed tosay "the delegation modal allows to select _no_ delegatee". So I'm able to push the button which makes me sign the transaction without selecting any delegatee. Which will definitely result in a failure.

**Comment by yornaath** [comment]
This should be fixed. **no build ready to test yet though**
