### ISSUE TITLE
[Court] State descriptions might need work

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#2061]
I think the state should be called _Appealed_ rather than _Appeal_ for the sake of consistency. Or is this the phase during which appeals can be made? Doesn't seem clear.

<img width="1920" alt="Screenshot 2023-12-08 at 11 04 51" src="https://github.com/zeitgeistpm/ui/assets/49552287/5c66d9ea-0397-483b-a487-498cc00090f1">

The description says "Jurors can now appeal the voted outcome." If the court case is already appealed, this description would be wrong.

<img width="1920" alt="Screenshot 2023-12-08 at 11 08 36" src="https://github.com/zeitgeistpm/ui/assets/49552287/c0c7e460-68c1-41e7-9204-bb1064f9fd5a">

It seems that _Reassigned_ is the "final" state. I think this is confusing. I would expect something to happen to a court case that's been "reassigned". How about "settled"? I mean, look at this: There are a couple of court cases, some of them are "closed" and others are "reassigned". Which one would a naive user expect to be in its "final" state? Especially given the reality that when a court case is appeal, it is assigned new jurors, this is confusing to me. Maybe I'm just being dense right now.

<img width="1920" alt="Screenshot 2023-12-08 at 11 06 47" src="https://github.com/zeitgeistpm/ui/assets/49552287/016e2798-9283-4a6e-b085-582c7e119c65">

"Waiting to be reassigned" sounds like the court case is waiting to be reassigned. In fact, it's the funds that are being reassigned, right?

<img width="1920" alt="Screenshot 2023-12-08 at 11 06 20" src="https://github.com/zeitgeistpm/ui/assets/49552287/9e8c9317-6091-4d01-8450-e1c5aa4205b3">

"All juror and delegator stakes were reassigned, by losers paying the winners." Sounds odd. The comma is definitely wrong.

<img width="1920" alt="Screenshot 2023-12-08 at 11 05 12" src="https://github.com/zeitgeistpm/ui/assets/49552287/3f0b08d7-dbb3-4926-bc57-cb52cf859ecd">

**Comment by yornaath** [comment]
1. "Appeal" is correct since it refers to the phase/round and not the state. It can be appealed, and isnt yet appealed.
2. I agree using the term "settled" rather than reassigned for the description of final state would be clearer on the frontend.
3. Yes the funds are being reassigned, not the case itself. Will try to make this clearer.
4. Showing who won on cases would be ideal, but needs indexer work @saboonikhil Since votes and court state is cleared from chain storage once the case reaches this stage.

**Comment by yornaath** [comment]
@maltekliemann Have fixed the first three, but third issue(showing who won on reassigned cases) needs a seperate issue.
