### ISSUE TITLE
[Court] Everyone can appeal a case

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#2062]
The description says that "jurors can now appeal the case". I believe any user can appeal the case by depositing a bond. If so, the bond should be mentioned. If not, then the button on the right should be greyed out if you're not a juror.

<img width="1920" alt="Screenshot 2023-12-08 at 11 24 00" src="https://github.com/zeitgeistpm/ui/assets/49552287/a841575f-79cd-45a6-8d2f-d44f3fd10b0a">

**Comment by yornaath** [comment]
@Chralt98 Can you clarify around who is able to appeal a case and bond costs?

**Comment by Chralt98** [comment]
Any address is able to appeal a case. The appeal costs can be read on the documentation page [here](https://docs.zeitgeist.pm/docs/learn/court#appeals).

**Comment by Chralt98** [comment]
However, on battery station the `AppealBond` is 5 ZBS, on the main-net it is `2000 ZTG`.
