### ISSUE TITLE
[Court] Contradictory percentage bars

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#2065]
I'm guessing these belong to different phases (dispute phase in the market view and appeal phase in the court view). Still, I think this is confusing.

<img width="1920" alt="Screenshot 2023-12-08 at 11 38 34" src="https://github.com/zeitgeistpm/ui/assets/49552287/a3d9a244-a77a-4aed-9df2-784b9765c7f6">

<img width="1920" alt="Screenshot 2023-12-08 at 11 38 23" src="https://github.com/zeitgeistpm/ui/assets/49552287/ea201e46-cc33-44d1-9450-c17563daba11">

**Comment by yornaath** [comment]
Yeah I think I can fix this by using the `CourtStageTimer` component that is used on the court case page(first screenshot) also on the market page(second screenshot) when the market has a active court case.

**Comment by yornaath** [comment]
This is now fixed on staging https://test.staging.zeitgeist.pm/court/8
