### ISSUE TITLE
Confusing rounding when reporting scalar market

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#2139]
Users might be unsure what they're reporting now:

<img width="1920" alt="Screenshot 2024-01-04 at 17 33 15" src="https://github.com/zeitgeistpm/ui/assets/49552287/260c59f4-72fb-466d-af4d-ef4043821d9e">

If you're doing the rounding to avoid expressions that are too long, I guess one solution would be to add "..." instead.

**Comment by Robiquet** [comment]
Remove number from button
