### ISSUE TITLE
Watch tutorial video doesn't point anywhere on create account page

### ISSUE THREAD

**Issue by robhyrk** [zeitgeistpm/ui#2220]
![Screenshot 2024-01-30 at 7 52 49 PM](https://github.com/zeitgeistpm/ui/assets/14626415/918d1a59-f1e7-4c91-8417-9a8afa404ef2)

**Comment by Robiquet** [comment]
https://www.youtube.com/playlist?list=PLdOlgpqyU8RP-ZK2A2qbcfxOlzoeuR6sx
