### ISSUE TITLE
Social sharing - market / market creation

### ISSUE THREAD

**Issue by TvrtkoM** [zeitgeistpm/ui#230]
Allow users to share market on social media

Social media message should contain (twitter)
- autogenerated image with market information in it - question, title and outcomes
- message from a user which is optional and depends on social media platform

Add the `share` button to market page, which opens sharing on certain social media platform. For start, the page should contain only the twitter icon

**Comment by TvrtkoM** [comment]
@mk26071980 a design for an image to be generated for social sharing.

...and regarding the `share buttons` think it would be ideal to have a general `social sharing` component that we could use on different pages. @Robiquet @yornaath

**Comment by lsaether** [comment]
Completed
