### ISSUE TITLE
Mismatched delegation to Jurors in Decentralized Courts

### ISSUE THREAD

**Issue by ltfschoen** [zeitgeistpm/ui#2310]
If you go to https://app.zeitgeist.pm/court and click the tab "Jurors".

It lists in the "Addresses" column with the addresses of the current jurors.

**Issues 1)** It doesn't correctly show the identity "Display Name" of all jurors that have set an identity. e.g. if there are two jurors A and B, it may only selectively shows the identity of juror A but not B.

It also lists a column "Total Stake" and "Delegators"
**Issues 2)** It shows the delegated stake against the wrong juror. e.g. if there are two jurors A and B and one delegator C that has delegated 100% only to juror B, currently it incorrectly shows juror A (instead of B) as having 1 delegator, and shows juror A (instead of B) as having had their total stake increased by that delegator C

**Issue 3** If you click the name or address in the row of juror A shown in the "Address" column, it takes you to the portfolio page of juror B (instead of A), and vice versa 

Sometimes it is actually shown correctly, but most of the time it isn't shown correctly.

This relates to this blogpost https://blog.zeitgeist.pm/decentralized-justice-zeitgeist-introduces-its-decentralized-court-system/

**Comment by yornaath** [comment]
@Robiquet @lsaether I think this is fixed in some pr I did a while back. Can any of you confirm?
