### ISSUE TITLE
Balances in portfolio are ordered by amount

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#2354]
Seems to me that the balances in the portfolio are ordered by the amount I hold in each balance. So as I spend some DOT transaction fees, my DOT balances on Polkadot slips below my ZTG balance on Zeitgeist and the order of those rows in the table change. That's confusing.

<img width="1920" alt="Screenshot 2024-03-06 at 20 27 19" src="https://github.com/zeitgeistpm/ui/assets/49552287/46129103-74df-415a-9f46-7e73cbebfab6">

**Comment by Robiquet** [comment]
Sort by balance size but don't reorder after initial render
