### ISSUE TITLE
Moving remaining DOT balance from Polkadot to Zeitgeist always fails/stuck

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#2355]
Always seems stuck on "Moving DOT to Zeitgeist...". Doesn't even produce a failed transaction. Moving part of my holdings to Zeitgeist works.

**Comment by Robiquet** [comment]
Have you checked subscan for transaction information?

**Comment by maltekliemann** [comment]
I can't see any transactions on Polkadot or Zeitgeist.
