### ISSUE TITLE
[Portfolio] Position details not shown for resolved ZTG markets

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#2386]
![image](https://github.com/zeitgeistpm/ui/assets/4950844/c91c1915-9f4f-452f-878e-513cfc8c83f4)

**Comment by yornaath** [comment]
Is this fixed? Cant seem to reproduce in either prod or dev?

**Comment by Robiquet** [comment]
@sajet006 Do you still see this issue?

**Comment by robhyrk** [comment]
Can't seem to reproduce either: closing issue.
