### ISSUE TITLE
Display Court rewards payouts

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#2387]

**Comment by Robiquet** [comment]
@saboonikhil do we index court rewards?

**Comment by saboonikhil** [comment]
> @saboonikhil do we index court rewards?

Would that be [MintedInCourt](https://github.com/zeitgeistpm/zeitgeist/blob/main/zrml/court/src/lib.rs#L361) event ?

**Comment by Robiquet** [comment]
Not sure, could you let us know? @Chralt98
