### ISSUE TITLE
Wrong Logo/Wrong Link

### ISSUE THREAD

**Issue by mk26071980** [zeitgeistpm/ui#254]
SubID logo is wrong -- missing the D's inside part. Portfolio is linked to the beta app

<img width="501" alt="image" src="https://user-images.githubusercontent.com/80706590/189992833-187cd3c5-80bd-4196-b194-5ba2c4963b05.png">

**Comment by lsaether** [comment]
Where is the source of this logo @mk26071980 ?

**Comment by mk26071980** [comment]
here:

![SubID_black](https://user-images.githubusercontent.com/80706590/197868950-97663a32-1a19-4636-9cdc-aca047a9ea21.svg)
![SubID](https://user-images.githubusercontent.com/80706590/197868959-647096da-56b6-4a1b-81b2-202b71ba930c.svg)

Or in Figma under Market tab https://www.figma.com/file/qe6BhxbYH06MXOf1Lkuv9i/App_v1.00.01?node-id=1%3A7793

**Comment by lsaether** [comment]
Thanks!
