### ISSUE TITLE
Reduce page load times by 10x

### ISSUE THREAD

**Issue by davidhperry** [zeitgeistpm/ui#255]
Load times are generally slow and inconsistent. For example, here are time load times for https://app.zeitgeist.pm/ (index page):

29.71s
16.39s
13.3s
1m10.48s
15.43s
48.57s
14.45s
49.44s
1m25s
16.59s

My environment: Mac, Chrome (v105.0.5195.102), 8.08 Mbps download w/ ping 5ms

**Comment by Robiquet** [comment]
What is it that you find yourself waiting on the most?

**Comment by robhyrk** [comment]
[lighthouse_summary.pdf](https://github.com/zeitgeistpm/ui/files/10231887/lighthouse_summary.pdf)

**Comment by robhyrk** [comment]
![Image](https://user-images.githubusercontent.com/14626415/207731257-83e1fb59-13ff-46c5-a086-2894251e1738.png)
