### ISSUE TITLE
Avatars are square

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#258]
<img width="289" alt="image" src="https://user-images.githubusercontent.com/4950844/190106553-b99c7119-bb99-410a-bb65-39b2eabf63a2.png">

https://app.zeitgeist.pm/markets/15

**Comment by yornaath** [comment]
They are round for me in production. Are you still experiencing this?

**Comment by Robiquet** [comment]
Looks like just a chrome issue actually

**Comment by Robiquet** [comment]
Fixed
