### ISSUE TITLE
Market close should have the time and timezone

### ISSUE THREAD

**Issue by Nathanpmyoung** [zeitgeistpm/ui#266]
The close time should be local times but need to work correctly.

**Comment by maltekliemann** [comment]
I'm bumping this. It would be really good to have the following features with regards to dates:

- Let the user specify the timezone, but always use UTC by default.
- Specify all dates with a timezone using a format like ISO8601 or some watered-down version of that
- (I'm dreaming here) Allow market creators to specify dates in the description in a way that the date changes according to the user's choice of timezone (so if I write: "The market will resolve to YES if Donald Trump tweets before 2022-04-01T00:00Z" and the user's timezone is CEST, then they see "The market will resolve to YES if Donald Trump tweets before 2022-04-01T01:00CEST").

**Comment by maltekliemann** [comment]
And while we're at it, can we use a 24h clock?

**Comment by Robiquet** [comment]
We should be storing dates in UTC and displaying them in the timezone and format based on the user's browser locale using APIs such as [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat). If that's not happening currently let us know and we can fix that. 

I don't think displaying dates in UTC timezone and ISO formatting isn't a great idea as it forces users to look up their timezone in relation to UTC/ do maths. ISO formatting can also be quite different for what certain users are used to

That being said, I can see a use case for specifying timezones on market creation as it could save some manual conversion when creating markets outside of your country.

**Comment by maltekliemann** [comment]
Bumping this because it's a really annoying problem.

**Comment by lsaether** [comment]
@TvrtkoM Can you complete this by the end of the week?

**Comment by TvrtkoM** [comment]
addded ability for user to set the timezone here https://github.com/zeitgeistpm/ui/pull/1621

@maltekliemann @Robiquet can you please see is this going to be fine?

date is set in specified timezone when market is created, but it's stored in UTC. Other date displays e.g. on market page are shown in UTC

![Image](https://github.com/zeitgeistpm/ui/assets/551965/984f4bc3-f479-43fd-8f5e-bac0a1983a9c)

In my opinion this should be a global setting (that's set in user settings modal) and all dates displayed in the app should use this locale.

**Comment by maltekliemann** [comment]
For now, this is fine. However...

> In my opinion this should be a global setting (that's set in user settings modal) and all dates displayed in the app should use this locale.

...I agree, it shouldn't be just be a setting during market creation. Let the user set the time zone somewhere in their account settings.

> Default locale should be locale that user browser is using and not UTC in my opinion

I don't have a strong opinion on defaults.

I think what's still unclear is whether or not we should add the time zone to each TOD displayed in the app. I think so, because it might not be clear to the user which time zone is used otherwise.

**Comment by Robiquet** [comment]
@maltekliemann My impression was that this feature was to help people create markets when the end date was in a different time zone, if that's the case wouldn't adding a global setting add more friction?

I think we should keep this feature as light touch as possible as the browser already handles a lot of the complexities around time zones already and I think most users will assume timezones are local.

**Comment by lsaether** [comment]
@maltekliemann Is this good enough functionality for the AC?
