### ISSUE TITLE
Enforce `Max*Ratio` contraints via frontend

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#271]
People keep running into the `Max*Ratio` errors, which trigger when you try to trade in/out more than 30% of the pool's balance. It's a very confusing concept, especially since you can't see what the pool balances are.

Maybe we can just enfore these constraints with the frontend and make sure that people don't even send transactions that would trigger these errors?

**Comment by maltekliemann** [comment]
I think this can be closed.

**Comment by Robiquet** [comment]
Done
