### ISSUE TITLE
Sorting markets by "Ends soon" presents wrong sort order

### ISSUE THREAD

**Issue by Tomen** [zeitgeistpm/ui#287]
**Steps to Repro**
1. All markets
2. Click on the sort order icon
3. Stay on the screen for an extended time and forget that you clicked the sort order icon
4. Click "ends soon"

**Actual Result:** The market that ends the latest is presented first. But as the short term memory fish that I am, I was completely confused, because I expected the soonest ending market first.

**Expected result:** The UI should help my short term memory fish brain to understand that I am seeing latest first because of the actions I performed, e.g. by changing the text of the button.

I think the problem with this whole filter row is that it is hard to distinguish what I am doing when I use it.

![image](https://user-images.githubusercontent.com/317186/190610280-d5f14ab4-e5d8-42ec-a00e-04407746f4c9.png)

**Comment by saboonikhil** [comment]
I think `Ends soon`/`Newest`/`Liquidity` fits more as a sorting option rather than a filter.

**Comment by TvrtkoM** [comment]
Can the `two arrows up` icon on the right help with this? They are used to sort markets ascending or descending for the selected combination of filters?

**Comment by TvrtkoM** [comment]
Can the `two arrows up` icon on the right help with this? They are used to sort markets ascending or descending for the selected combination of filters?

**Comment by TvrtkoM** [comment]
No response for 7 days.
