### ISSUE TITLE
Add a banner pointing to the launch blog post for NFTs

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/ui#294]
Right now we're just wasting the screen real estate for a banner image that only glitches. We should replace this with a banner advertising the Zeitgeist Avatar and links to the Zeitgeist Avatar blog post when clicked.

**Comment by mk26071980** [comment]
![Introduce_Avatars](https://user-images.githubusercontent.com/80706590/194904311-5ccaa368-7a37-4015-9fd4-5818a45ede2b.png)
