### ISSUE TITLE
Proposed markets don't show if scalar or category which is hard for advisory comittee.

### ISSUE THREAD

**Issue by Nathanpmyoung** [zeitgeistpm/ui#298]
In order for the advisory committee to approve markets they need to know whether they are scalar or category.

**Comment by Boibit** [comment]
![image](https://user-images.githubusercontent.com/61936910/211860289-c463569c-98f3-4e28-8f3f-a6b1c960b7bd.png)
Example market is live on app 1/11 https://app.zeitgeist.pm/markets/84

Pretty much what was mentioned in earlier comments.

-There is no way to tell what the scalar range for a market is which is quite important for advisory committee. For example: If we were to approve the market seen above, we would have no way of checking if the top of the range is actually higher than the current number of Youtube subscribers.

-There is no way on the front end to see if the market is a scalar market at all. It could just be a categorical market with clever token/outcome names. We would never want to approve anything like that. 

We would need something to display the market type and range visually, so likely this should move to design pipeline with 7+ priority imo.

**Comment by robhyrk** [comment]
@mk26071980 are there design elements we could incorporate to show the market type on this page? Maybe something like including the market type with the categories?  Could also include what was done in #314 for this page too.

**Comment by mk26071980** [comment]
https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?node-id=3970%3A22391&t=ikl65aPOLDdNa1Hn-1
