### ISSUE TITLE
Can't see scalar range in proposed scalar market

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#314]
Knowing the scalar range is an important part of the review process, so we need to be able to tell what the range is.

**Comment by TvrtkoM** [comment]
related to #313

**Comment by lsaether** [comment]
@mk26071980  Please add link to figma

**Comment by mk26071980** [comment]
<img width="836" alt="image" src="https://user-images.githubusercontent.com/80706590/220322748-fffee2f5-095d-47d9-9f8a-7ed0e46b3aa4.png">

https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?node-id=3959%3A22426&t=JPYRp7LYT6IfYn2N-1
