### ISSUE TITLE
Liquidity Withdrawal

### ISSUE THREAD

**Issue by jimmy-tudeski** [zeitgeistpm/ui#316]
I encountered the error when trying to remove liquidity from the pool as market creator/owner. 

When trying to remove anything less than 100%, there is an error popping up after signing tx.

"A transferal of funds out of a swaps pool was below a threshold specified by the receiver."

![image](https://user-images.githubusercontent.com/68714636/192051207-6827c151-f26a-4229-ac35-d70c5555e6f6.png)

When You try to remove 100% of liquidity from the pool, it gives the below error:

"A pool balance dropped below the allowed minimum."

![image](https://user-images.githubusercontent.com/68714636/192051458-2f86dd75-e875-43e3-9d2a-d49b2b1491e6.png)

The operations were performed on the LP:
https://app.zeitgeist.pm/liquidity/22
The market is:
https://app.zeitgeist.pm/markets/31

**Comment by maltekliemann** [comment]
Some details on this... It seems like the `min_asset_amount` is specified incorrectly by the UI. For example, the pool contains 1827 ZTG, but when withdrawing about 25% of the liquidity, the minimum amount of ZTG specified is 511.7 (OP is the only pool owner). It should be less than a quarter of the amount of ZTG held in the pool.
