### ISSUE TITLE
Add note on why buttons are greyed-out

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#318]
For example, if you don't have enough funds left in the account, the button for market creation is greyed out, but you might not have any clue as to why.

**Comment by mk26071980** [comment]
https://www.figma.com/file/UBJxc5KRoCRLZuS1Zqa0Kx/Sprints?node-id=0%3A1

<img width="840" alt="image" src="https://user-images.githubusercontent.com/80706590/194903909-d90c75e9-f029-4ab8-b9c9-a05ff590b143.png">

<img width="875" alt="image" src="https://user-images.githubusercontent.com/80706590/194904000-1e27f968-96ab-44af-911d-4e159637821b.png">

**Comment by maltekliemann** [comment]
I really like the checkmarks. :thumbsup:
