### ISSUE TITLE
Rework Popular Markets

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/ui#320]
Popular markets currently takes up too much screen space on the index page. It can be reworked to live in the sidebar or on a separate page instead.

**Comment by TvrtkoM** [comment]
![image](https://user-images.githubusercontent.com/551965/193613920-4311b3dc-95d3-4e13-a5da-8abf6e7d0423.png)

**Comment by mk26071980** [comment]
https://www.figma.com/file/UBJxc5KRoCRLZuS1Zqa0Kx/Sprints?node-id=0%3A1

<img width="758" alt="image" src="https://user-images.githubusercontent.com/80706590/194903608-73372d6f-44d1-4340-a218-4f0fd1f38085.png">

**Comment by TvrtkoM** [comment]
popular categories have been reworked
