### ISSUE TITLE
Integrate grace period, oracle duration, and dispute duration

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/ui#330]
Upcoming in the next release, the dispute period will now be configurable by the market creator. The new configurable variables are `grace_period`, `oracle_duration`, and `dispute_duration`. 

See https://github.com/zeitgeistpm/zeitgeist/pull/732 for context.

## Needed Changes

- [ ] Add the new configuration options to the market creation flow.
- [ ] Display the configured values on the market page with information about what each of the configuration values will mean for how the market is resolved.

**Comment by mk26071980** [comment]
https://www.figma.com/file/UBJxc5KRoCRLZuS1Zqa0Kx/Sprints?node-id=77%3A2678

<img width="799" alt="image" src="https://user-images.githubusercontent.com/80706590/195065969-eb0a7266-3635-4e3b-8953-160ed58dd30b.png">

Preferred option. Need to set relevant values for each period
