### ISSUE TITLE
Allow market creator to set the initial prices using weights

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/ui#331]
The initial market prices should be configurable by the market creator / initial liquidity provider by setting the weights of the pool.

**Comment by Robiquet** [comment]
I think this feature has potential to mitigate the issues we have related to impermanent loss see: https://docs.balancer.fi/products/balancer-pools/weighted-pools

With big differences in weights trading could become less intuitive so we should display additional information such as price impact #301 

[Balancer](https://app.balancer.fi/#/pool/create) has a nice way of presenting weights when creating a pool, we should consider a similar design
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/4950844/194303778-1061aaaf-a190-4673-b719-eca59cf7dbf0.png">

**Comment by mk26071980** [comment]
https://www.figma.com/file/UBJxc5KRoCRLZuS1Zqa0Kx/Sprints?node-id=77%3A2678

<img width="787" alt="image" src="https://user-images.githubusercontent.com/80706590/195050532-6f354b42-3c01-416e-8835-71540f58ab60.png">

**Comment by maltekliemann** [comment]
@mk26071980 Looks very cool. I don't think we need the _amount_ column, though, because the amount must always be the same for all assets.

**Comment by Robiquet** [comment]
@maltekliemann we need somewhere to set the amount though. Currently when they change the amount in one of the columns it sets it for all

**Comment by maltekliemann** [comment]
@Robiquet Ok, that's fine.

**Comment by Robiquet** [comment]
Done
