### ISSUE TITLE
Price history interpolates strangely between events

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#339]
The price history view seems to interpolate between prices with [sigmoid functions](https://en.wikipedia.org/wiki/Sigmoid_function):

<img width="1920" alt="Screenshot 2022-10-08 at 15 36 26" src="https://user-images.githubusercontent.com/49552287/194766267-74041f9e-5982-443f-8e66-5d989b7234b2.png">

I'm pretty sure the price didn't actually develop the way the history displays. A hot-fix would be to interpolate by using the last known value (this will give you a [step function](https://en.wikipedia.org/wiki/Step_function) instead). In a perfect world, I guess we would be using candle sticks instead?

**Comment by Robiquet** [comment]
Doesn't seem like an option in our chart library https://recharts.org/en-US/api/Line

**Comment by Robiquet** [comment]
Actually I think it's this: https://recharts.org/en-US/api/Line#type

**Comment by Robiquet** [comment]
@maltekliemann which one do you think it should be out of these? https://github.com/d3/d3-shape#curves

**Comment by maltekliemann** [comment]
Oh, nice. I think it should be `stepAfter`.

**Comment by lsaether** [comment]
Will be addressed in the new chart revisions
