### ISSUE TITLE
Create a 'Save Draft' feature

### ISSUE THREAD

**Issue by Boibit** [zeitgeistpm/ui#342]
Converted to issue on 10/10

App users have no way to save their market as a draft currently. Adding this feature would be a massive UX improvement in that users could pause the creation process and ask for review when deploying a market. 

This feature could also improve the UX of advised markets if submitted markets are submitted in a Draft state and the user has a chance to edit after review without committing to a ZTG bond/slash scenario.

**Comment by lsaether** [comment]
@yornaath What is the status of save draft with the new market creation flow?

**Comment by Robiquet** [comment]
> @yornaath What is the status of save draft with the new market creation flow?

Form state is saved to local storage by default
