### ISSUE TITLE
More compact front page

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#344]
Suggestion from community member:
"This leads me to my second point, which is if the markets were to load at a reasonable speed, they should be much more visible on page landing. Why hide the most relevant content? As much as I like the cool hero graphic - I quickly have to 'ignore' it every time I land on the page and scroll to what I'm really looking for - the markets. 

This point also perhaps stands for the "popular topics" and how much size they take up/how much further down they push the markets 
forgive my crude mockup, but to illustrate.."

![image](https://user-images.githubusercontent.com/4950844/195022210-369f30da-5574-4646-abbe-6c2a92d8606c.png)

**Comment by mk26071980** [comment]
It's already here https://github.com/zeitgeistpm/ui/issues/320

**Comment by Robiquet** [comment]
> It's already here #320

Doesn't that one just delete the Popular topics? This suggestion seems different
