### ISSUE TITLE
Revisit fonts in throughout the application

### ISSUE THREAD

**Issue by mk26071980** [zeitgeistpm/ui#345]
All the btn text should be Space Grotesk, not Lato (like in Settings) or Kanit.

**Comment by TvrtkoM** [comment]
Should be: Kanit for the logo, Lato for text, Space grotesk for the headlines and buttons and roboto mono for numericals.

**Comment by lsaether** [comment]
What exactly needs to be changed here?

**Comment by TvrtkoM** [comment]
@lsaether All fonts in app checked are according to design (my first comment here) and changed if aren't.

**Comment by lsaether** [comment]
Awesome!
