### ISSUE TITLE
Charts of marktes 0 and 2 not loading properly

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#347]
The chart of market 0 looks like it only has one data point and doesn't display correctly. The chart of market 2 is stuck loading.

<img width="1304" alt="Screenshot 2022-10-13 at 21 13 53" src="https://user-images.githubusercontent.com/49552287/195689273-b0011715-1fb0-41f1-b45f-c7382ba71e97.png">
<img width="1286" alt="Screenshot 2022-10-13 at 21 14 12" src="https://user-images.githubusercontent.com/49552287/195689299-dec6d988-a757-4d7a-ab48-40fe4ad892e2.png">

**Comment by Robiquet** [comment]
I think this is because we only pull the last 28 days of price data and there probably haven't been any trades within that time. Perhaps we should pull all data since market creation
