### ISSUE TITLE
Use Twitter-style checkmark for approved advised markets

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#357]
As discussed in the meeting earlier. Just an idea, but I think this feels more intuitive than the warning sign that we see for permissionless markets right now.

**Comment by Robiquet** [comment]
Done 
<img width="217" alt="image" src="https://user-images.githubusercontent.com/4950844/233027971-2e4aac8a-fa46-4905-bdfd-e55c7011c655.png">
