### ISSUE TITLE
Dispute history unclear

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#362]
The _disputed outcome_ is the outcome that was suggested by the disputant. But what was the outcome that was reported by the oracle? In a yes-no market, this is not a problem, but when three assets are presented, it's no longer clear what happened before the dispute. I think an actualy dispute history might fix this.

Also, the diispute duration bar seems broken.

<img width="1280" alt="Screenshot 2022-10-22 at 10 33 38" src="https://user-images.githubusercontent.com/49552287/197329760-0da8bc3f-a777-4e80-9b48-6f3a702d4a6f.png">

**Comment by Robiquet** [comment]
Old component
