### ISSUE TITLE
Display start date on market details page

### ISSUE THREAD

**Issue by davidhperry** [zeitgeistpm/ui#43]

**Comment by TvrtkoM** [comment]
is this something we can do in upcoming sprints?

**Comment by mk26071980** [comment]
New design has the start date



![Image](https://user-images.githubusercontent.com/80706590/218084555-0971c9f2-a250-4dfc-a047-35e2ae7b4c99.png)

**Comment by lsaether** [comment]
It should be the start date as in when the market becomes active, not when the market was created.

**Comment by mk26071980** [comment]
<img width="978" alt="image" src="https://user-images.githubusercontent.com/80706590/220574465-9e4366e5-6cbf-4b93-b75a-a521b4906c4c.png">
https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?node-id=3970%3A22391&t=EKM80QDlLKSgCDGu-1

**Comment by Robiquet** [comment]
Think we were just going to replace "Created" with "Starts"

**Comment by mk26071980** [comment]
it's just an option. Just replacing created with starts is better
