### ISSUE TITLE
Replace NEXT_PUBLIC_ENVIRONMENT_NAME

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#431]
Doesn't seem like we have this configured for production but it looks like some code relies on this. Could be replaced with `VERCEL_ENV` which is provided by Vercel

**Comment by lsaether** [comment]
Looks like we can close this

![image](https://user-images.githubusercontent.com/25539605/218473099-938c5998-dbe0-45bd-8e69-45131d765b2f.png)

![image](https://user-images.githubusercontent.com/25539605/218473130-8f419b07-d1fc-4120-b3d0-753f305264c6.png)
