### ISSUE TITLE
Asset colors sometimes clash with the background

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#444]
Same market, different themes. The dark graph is very hard to see in dark mode.

<img width="1068" alt="Screenshot 2022-11-22 at 22 25 23" src="https://user-images.githubusercontent.com/49552287/203424558-29c8daee-8010-4ba8-b604-783d51a3b312.png">
<img width="1190" alt="Screenshot 2022-11-22 at 22 25 00 1" src="https://user-images.githubusercontent.com/49552287/203424564-ccf08c95-76bf-41c0-8255-5b131bb58e24.png">

**Comment by lsaether** [comment]
@TvrtkoM Would it be possible to disallow colors that fall in a certain range (in our case, any color that gets "too white") such as colors greater than rgb(213, 213, 213) ?

**Comment by TvrtkoM** [comment]
Bumping this issue to keep in mind for new market creation page
