### ISSUE TITLE
Market description looks strange in light mode

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#457]
https://app.zeitgeist.pm/markets/68

Dark mode looks fine, but light mode looks strange. Could this possibly be the result of copying formatted text from other sources (like Discord)?

<img width="1920" alt="Screenshot 2022-11-24 at 20 24 09" src="https://user-images.githubusercontent.com/49552287/203854074-f7ee5dc4-8e22-420f-ac9c-5ae598e59c8e.png">

**Comment by Robiquet** [comment]
Yeah looks like some styling got copied across. Probably the market was created in Dark mode where it looks fine. We are removing dark mode so hopefully we won't have this issue

**Comment by maltekliemann** [comment]
The problem I see with that solution is that users are still able to use terrible styling. For example, what if someone wants to use green letters on a red background. Would that be possible? And do we want to allow that even though it makes the app look pretty bad?

**Comment by Robiquet** [comment]
Maybe we can just remove styling. Though don't really see why a user would deliberately make their market look terrible

**Comment by lsaether** [comment]
Also apparent on market 65 and reported here https://github.com/zeitgeistpm/ui/issues/442

I would remove styling from the description. I can't think of any non-aesthetic reason we should allow it, and a whole bunch of possible unintended effects that can happen by allowing it.

**Comment by lsaether** [comment]
My hypothesis is that the styling tags get added when copy-pasting a market over from Notion.
