### ISSUE TITLE
Timeline showing incorrect time remaining

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#464]
The market was just disputed, but the dispute timeline appears to be three-quarters full.

<img width="1536" alt="Screenshot 2022-11-28 at 17 33 21" src="https://user-images.githubusercontent.com/49552287/204331382-6ad3ce6e-0f46-4a96-bbdd-45f8453bca44.png">

**Comment by maltekliemann** [comment]
Probably related to #353.

**Comment by Robiquet** [comment]
Old component
