### ISSUE TITLE
Can't see market deadlines for advised market

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#469]
The market view for advised markets doesn't show the deadlines (grace/report/dispute periods) of the market. This makes it difficult to decide if the market is reasonably configured.

**Comment by TvrtkoM** [comment]
Since deadlines are set in block numbers maybe we should display the timer for deadlines in block numbers also instead of calculating the timestamps from block numbers which can be inaccurate since not every block is 12s.

For this it would be also nice to have market closed block number indexed.

**Comment by maltekliemann** [comment]
I think this can be closed now.
