### ISSUE TITLE
Styling for market filters

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/ui#502]

**Comment by lsaether** [comment]
@mk26071980 Please add figma link

**Comment by Robiquet** [comment]
I think this is the design 
<img width="713" alt="image" src="https://user-images.githubusercontent.com/4950844/220083874-8b57fabd-6d71-40c0-8703-60c9afce5844.png">
https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?node-id=3970%3A22390&t=VZsAlSDZCYEfzZf8-0
Though, we might need to review the current categories that we're offering 
<img width="894" alt="image" src="https://user-images.githubusercontent.com/4950844/220084070-afb6401c-a3ee-4c3b-9431-e1513618cc0b.png">

**Comment by lsaether** [comment]
@mk26071980 How does this look once we start adding more categories?

**Comment by lsaether** [comment]
@mk26071980 How do the Currency and Status dropdowns look?

**Comment by mk26071980** [comment]
https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?node-id=3970%3A22390&t=EKM80QDlLKSgCDGu-1
