### ISSUE TITLE
Display the reject reason for a market

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#504]
We emit a reason when rejecting a proposed market. It would be nice to display that to the user. Might be difficult because the market gets deleted. Would it help if we didn't delete the rejected market on chain?

Not high priority.

**Comment by lsaether** [comment]
@maltekliemann Does the reject reason get stored anywhere?

**Comment by lsaether** [comment]
It's probably not necessary to keep the market existent in the chain storage, as long as we can rely on Subsquid for displaying the data for the destroyed market.

**Comment by maltekliemann** [comment]
> @maltekliemann Does the reject reason get stored anywhere?

No, it is just part of the `MarketRejected` event.

**Comment by lsaether** [comment]
cc @saboonikhil Is this available in subsquid?

**Comment by saboonikhil** [comment]
> cc @saboonikhil Is this available in subsquid?

Should be available by this week ends: https://github.com/zeitgeistpm/zeitgeist-subsquid/issues/237
