### ISSUE TITLE
Adjust styling for index page to reflect latest designs

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/ui#512]
The latest designs incorporate some changes for the index page. These include a larger banner, changes to the categories and the overall layout on the page. The styling should be adjust to align to the newest designs. Note: this should not touch the sidebar or the top navigation bar yet, those will be handled in future issues.

Everything contained below and to the right of the red lines in this screenshot should be adjusted to complete this issue.

<img width="291" alt="image" src="https://user-images.githubusercontent.com/25539605/208324324-5be9cb50-b5c2-471a-a3eb-cb4ecbd51f5f.png">

**Comment by robhyrk** [comment]
although we needed to break this into smaller issues for each component there is still the task of adjusting the layout/breakpoints for this page
