### ISSUE TITLE
Chart: Add time series selectors for normal time periods: 24hrs, 7days, 14days, 30d, 90d, 1y, all time

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/ui#513]
We should add a selector onto the Market page that controls the time period that is displayed by the chart. The component should look something like this one (taken from CoinGecko) 
<img width="479" alt="image" src="https://user-images.githubusercontent.com/25539605/208324424-43c0fd6d-977b-4ad3-b65d-e308005cb3ac.png">

Each of the selectors should change the x-axis of the chart to have ranges that reflect the selected time period.

**Comment by Robiquet** [comment]
We have a few options for now, but can add more:

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/4950844/225373933-0a8cb30d-af45-4331-b70d-52740a0dcef4.png">
