### ISSUE TITLE
Reduce bundle sizes

### ISSUE THREAD

**Issue by robhyrk** [zeitgeistpm/ui#522]
[Performance Analysis](https://www.notion.so/zeitgeistpm/Performance-analysis-af50da6ec6ff475396d26f60de9aaf3f)

Reference to #255

**Comment by TvrtkoM** [comment]
i think @yornaath did something related inside `next.config.js`, but after nextjs was upgraded the app failed to boot, because some runtime errors started to show up

**Comment by TvrtkoM** [comment]
Think we should investigate how much static generation influences the build size and balance out static / dynamic data loading.
