### ISSUE TITLE
Load min data and display as early as possible upon app load

### ISSUE THREAD

**Issue by robhyrk** [zeitgeistpm/ui#526]
[Performance Analysis](https://www.notion.so/zeitgeistpm/Performance-analysis-af50da6ec6ff475396d26f60de9aaf3f)

_Move away from usage of stores for some data as they impose requirements on what data is required. Instead we should load the minimum amount of data and display as early as possible, react-query could be used to mange the complexities of fetching and caching https://tanstack.com/query/v4/docs/overview_

Reference to #255

**Comment by TvrtkoM** [comment]
most of this is done with react-query implementations for markets list and liqudity pools. We still need to remove the usage of mobx stores from the app after we completely switch over to new sdk and remove usage of mobx stores
