### ISSUE TITLE
Utilize static generation for slower moving parts of the app

### ISSUE THREAD

**Issue by robhyrk** [zeitgeistpm/ui#527]
[Performance Analysis](https://www.notion.so/zeitgeistpm/Performance-analysis-af50da6ec6ff475396d26f60de9aaf3f)

_Utilise static generation for slower moving parts of the app, or places that require SEO. Need to figure out a way to combine static generation with dynamic elements (if it’s even possible)_

Reference to #255

**Comment by TvrtkoM** [comment]
@Robiquet added static generation for index and market details pages.maybe there are other parts of the app that can benefit from using static generation.
