### ISSUE TITLE
Market page not compensating for 'Grace Period'

### ISSUE THREAD

**Issue by Boibit** [zeitgeistpm/ui#529]
![Image](https://user-images.githubusercontent.com/61936910/208642119-2b07756e-80ec-43e2-8469-cb8b6c9ea6c5.png)

![Image](https://user-images.githubusercontent.com/61936910/208642171-fa196ff3-3cbd-41ba-8390-6f6d8308feef.png)

![Image](https://user-images.githubusercontent.com/61936910/208643107-c1f979dc-263d-427e-bf69-1247d109fc82.png)

This market was created on Dec. 7th with a closing date of Dec. 14th, a grace period of just over 4 days(Dec. 19th) and a reporting period of 4 days after the end the grace period (Dec. 23rd). However, upon checking the market on Dec. 19th it displays as if the reporting period is concluded with "Oracle failed to report. Reports open to all." Likewise the outcomes have active "Report outcome"  buttons that anybody can click and attempt to report. Upon submitting the report you receive an error "The report is not coming from designated Oracle."

The market should still have 3 days of reporting window at the time of these screenshots.

**Comment by yornaath** [comment]
@Boibit The errors that is being notified `The report is not coming from designated Oracle.` is correct right? Since any user is able to submit it even though they shouldnt(since its actual state is in reporting state where only oracle should be able to report)?

**Comment by yornaath** [comment]
@saboonikhil Need deadlines on `Market` to continue with this. https://github.com/zeitgeistpm/tools/issues/242

**Comment by Boibit** [comment]
> @Boibit The error that is being notified `The report is not coming from designated Oracle.` is correct right? Since any user is able to submit it even though they shouldnt(since its actual state is in reporting state where only oracle should be able to report)?

Correct.

**Comment by yornaath** [comment]
Working on some utility to fix this and also the timeline(in a different issue) in the @zeitgeistpm/sdk-next#5 issue
