### ISSUE TITLE
Markets page - prediction calculation is not consistent

### ISSUE THREAD

**Issue by TvrtkoM** [zeitgeistpm/ui#537]
Steps to reproduce:

- go to https://staging.zeitgeist.pm/markets?status=Active&ordering=Newest&liquidityOnly=true
- not the prediction value inside market cards
- focus address in browser's address bar then, focus the webpage again
- after doing previous step a couple of time, prediction value of market changes

![image](https://user-images.githubusercontent.com/551965/208879547-b7428d84-e093-4027-ac80-707deeabaa63.png)

![image](https://user-images.githubusercontent.com/551965/208879602-62e93efd-2442-41a5-a6d5-d82d7923df6d.png)

**Comment by lsaether** [comment]
related to #550

**Comment by saboonikhil** [comment]
Is this still happening? Haven't been able to reproduce it on my side.
