### ISSUE TITLE
Markets seem to display the prices of other markets

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#539]
I manually deployed a pool with non-equal asset weights for this market: https://app.zeitgeist.pm/markets/75. Instead of displaying the prices 0.1 and 0.9 for YES and NO, it displayed 0.5 for both. Later removed liquidity so people don't get confused.

But here's where it gets really interesting. The FTX market (id 65) after withdrawing liquidity now looks like this in the market overview

<img width="1920" alt="Screenshot 2022-12-22 at 22 52 56" src="https://user-images.githubusercontent.com/49552287/209233572-8b147b6e-0d4e-4ae3-ae5b-3be363d7aadd.png">

And like this in the market details:

<img width="1920" alt="Screenshot 2022-12-22 at 23 09 47" src="https://user-images.githubusercontent.com/49552287/209234349-4ba1df6c-205e-4806-bdb7-0a3813ffb9d0.png">

Check out the prices. Is that a coincidence?

**Comment by lsaether** [comment]
- Need to test if still is a bug in current main / staging.

**Comment by TvrtkoM** [comment]
For the FTX market (id 65), by querying the chain i get this prices:
```
  '{"categoricalOutcome":[65,0]}' => 0.099710602254274019965,
  '{"categoricalOutcome":[65,1]}' => 0.90034003543178336892
```
which correspond to the second screenshot.

block hash for block no. 1944439 - 0x8208fe42e0b3cee5d71cc2d24822241b117ec1c133afca255ce27d94bd6106d6
pool account - dE1VdxVn8xy7HFNWfF1dwJGArAQpsb2oAmPavM9S8BvuSWmmf
