### ISSUE TITLE
Making profit/loss clearer

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#55]
<img width="626" alt="image" src="https://user-images.githubusercontent.com/4950844/137697637-bcae3723-2fc0-4626-9fb0-6e8fa2e85cbe.png">
Maybe we could look at displaying profit/loss for resolved markets as a starting point

**Comment by mk26071980** [comment]
![Image](https://user-images.githubusercontent.com/80706590/221825521-fd4b937b-fd6f-42dd-94c4-f917a3196eac.png)

https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?node-id=3970%3A22392&t=30U3x0P2jOL33H8b-1
