### ISSUE TITLE
Portfolio page - bugged redeems

### ISSUE THREAD

**Issue by Boibit** [zeitgeistpm/ui#556]
Note: I didn't track specific balances, but neither account received/lost more ZTG than expected.

When viewing the Portfolio page I noticed that I could 'redeem all' for an absurd amount of ZTG  
![Image](https://user-images.githubusercontent.com/61936910/211345697-20f28250-9bc0-4155-b0df-b40502f2bbf9.png)

As you can see above, the only Scalar market in my portfolio is the 'world cup goals' which has a bugged 24hr % change. 

When redeeming the tokens from that market I got this:
![Image](https://user-images.githubusercontent.com/61936910/211348463-562cbf52-6360-42ec-a5cd-1f08b0d5fb91.png)

When using a different account, the LP for the market:
![Image](https://user-images.githubusercontent.com/61936910/211348758-37a78fbd-56b7-47a7-94c7-478bf789a80a.png)
![Image](https://user-images.githubusercontent.com/61936910/211348852-ee2d9f1b-4c87-4f70-9ed3-b0191ac384c9.png)

**Comment by lsaether** [comment]
- possibly related to change in bounds being multiplied by 10**10

**Comment by saboonikhil** [comment]
Old scalar markets needs to be rescaled on subsquid as well, might be connected.
