### ISSUE TITLE
Markets created after 12/23 seem to have bugged charts

### ISSUE THREAD

**Issue by Boibit** [zeitgeistpm/ui#558]
Seems that the indexer is not accounting for auto arbitrage causing broken chart prices and broken 'Prediction' displayed on the market card. 

IE: Market 78 is displaying a Prediction of 'YES' on the market card when the prediction should be 'NO'. 
![Image](https://user-images.githubusercontent.com/61936910/210219660-65016674-41a1-4e9e-ade8-4b4ba285dbf6.png)

Inside the Market Page the prices are displaying -39ztg~ and 1.1ztg~.
![Image](https://user-images.githubusercontent.com/61936910/210598537-a22d52a9-26c3-4124-a89c-38b0de4e920e.png)

but the outcome prediction % is actually YES: 29%, NO: 71%.
![Image](https://user-images.githubusercontent.com/61936910/210598691-d721ae02-35ff-4dff-bdda-483bd70f5d94.png)

**Comment by saboonikhil** [comment]
Post mapping of arbitrage events, charts look good now. Could you confirm?

**Comment by Boibit** [comment]
Looks good on live 👍
