### ISSUE TITLE
trade slip submit transaction button should be disabled when total loss / gain is zero

### ISSUE THREAD

**Issue by TvrtkoM** [zeitgeistpm/ui#562]
submitting transaction should be disabled in case total loss / gain is zero - all values in inputs are zeroes.,
atm I am able to submit buying 0 outcomes which gives error in console

```
TypeError: Cannot destructure property 'index' of 'data.toHuman(...).error.Module' as it is undefined.
```

**Comment by lsaether** [comment]
Tradeslip to be replaced
