### ISSUE TITLE
Toaster messages alignement

### ISSUE THREAD

**Issue by mk26071980** [zeitgeistpm/ui#57]
Move to the left to align with the box 
![image](https://user-images.githubusercontent.com/80706590/137707176-5c951bf2-9bc5-4e24-9f67-ef63f389e380.png)

**Comment by Robiquet** [comment]
<img width="365" alt="image" src="https://user-images.githubusercontent.com/4950844/191768039-0eeff900-eeb8-4ff0-9be1-21ebd07e1d0e.png">
Looks done
