### ISSUE TITLE
Handle scalar price overlap

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#571]
If the scalar price is the same as or close to one of the bounds, there is overlap and it's not clear what's going on:
<img width="796" alt="image" src="https://user-images.githubusercontent.com/4950844/211777680-44646a96-e7d4-48eb-9a37-bb49c62fdfd5.png">

**Comment by lsaether** [comment]
@mk26071980 We still need the component on the market page. It's already done for card.

**Comment by mk26071980** [comment]
<img width="666" alt="image" src="https://user-images.githubusercontent.com/80706590/220321604-f70f145e-f951-40a4-8fce-12bbcbc34fea.png">

https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?node-id=3970%3A22391&t=JPYRp7LYT6IfYn2N-1
