### ISSUE TITLE
Uploading image seems to fail sometimes

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#579]
For example https://app.zeitgeist.pm/markets/85

**Comment by maltekliemann** [comment]
The image provided by the user is 6.460 bytes large, a `.png` and has dimensions 113 × 128.

**Comment by TvrtkoM** [comment]
related issue #548

**Comment by TvrtkoM** [comment]
> The image provided by the user is 6.460 bytes large, a `.png` and has dimensions 113 × 128.

In this case the image is actually `svg` although it passed since the extension was `.png`. Browser API seem to check files only by extension and nextjs doesn't allow loading svg by default - https://nextjs.org/docs/api-reference/next/image#dangerously-allow-svg
