### ISSUE TITLE
Fees not displaying properly in trade slip

### ISSUE THREAD

**Issue by Boibit** [zeitgeistpm/ui#595]
Trading fee preview shows: 7 ZTG  (0.07%)
Should be: 1.36 ZTG (7%)

-Trading fee seems to be calculating 7% of the KC tokens being bought and displaying that as an equivalent amount of ZTG for a fee.
-The fee percent shows 0.07% which can misleading from the actual value of 7%

![Image](https://user-images.githubusercontent.com/61936910/213246823-3edb85d2-d332-4be5-bbfd-d0d868767391.png)

**Comment by Robiquet** [comment]
Trading fee needs to be multiplied by 100 to be shown as a percentage
