### ISSUE TITLE
Prices on resolved market are incorrect

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#619]
See https://app.zeitgeist.pm/markets/75. The price history looks correct (YES almost zero, NO almost one), but the prices in the chart are one for NO (the winning outcome) and almost one for YES (definitely not).

<img width="1920" alt="Screenshot 2023-01-24 at 12 28 17" src="https://user-images.githubusercontent.com/49552287/214280521-36673202-8c0d-4e2d-84ca-809dd9331abc.png">

**Comment by Robiquet** [comment]
Fixed on latest version (releasing soon)
<img width="815" alt="image" src="https://user-images.githubusercontent.com/4950844/214303114-2b2e3d5c-1e47-4e7c-9fc5-ee212aab7e69.png">
