### ISSUE TITLE
Display Max Price and Average Price on buy/sells

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/ui#628]
Users want to see where the prediction will move to (max price) and what their entry will be (avg price) without doing mental mathematics.

**Comment by Robiquet** [comment]
Price impact % or something else?

**Comment by lsaether** [comment]
Price impact would still require someone to do math to figure out where the price moves to, so I think we just need to display max price (Aka price after trade). Average price is probably lesser importance.

**Comment by mk26071980** [comment]
![Image](https://user-images.githubusercontent.com/80706590/218085381-68b2b5ba-992b-4957-a2b9-5a42cad525f5.png)
