### ISSUE TITLE
Show average purchase price in ticker

### ISSUE THREAD

**Issue by Nathanpmyoung** [zeitgeistpm/ui#638]
It is frustrating not to be able to see the average price you are purchasing your tokens at. Makes it hard to know how many to buy

**Comment by Robiquet** [comment]
Think this is related to #628

**Comment by mk26071980** [comment]
Modals tab 


![Image](https://user-images.githubusercontent.com/80706590/218084794-d4624174-6b7b-432f-ba64-b3a6b9bf2027.png)
