### ISSUE TITLE
Have % on market search page so people can decide whether to bet

### ISSUE THREAD

**Issue by Nathanpmyoung** [zeitgeistpm/ui#641]
The market % should be large and easy to understand.

**Comment by Robiquet** [comment]
New market card design is here: https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?node-id=3094%3A19855&t=huyZLBaiofpkVHbF-0

Does that cover it?
<img width="289" alt="image" src="https://user-images.githubusercontent.com/4950844/215747735-19ae5297-9246-4178-9645-541e4452eae9.png">
