### ISSUE TITLE
Display average entry price / total cost of position on the portfolio page

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#657]
Using the transaction history we should be able to calculate how much a user spent to acquire a token. That way they can know if they are in profit or not

Not sure what is best "Average entry price" or "Total Cost" or something else?

**Comment by Robiquet** [comment]
Discussed, should be "Total Cost"

**Comment by robhyrk** [comment]
It would be nice to have a PnL section too - #1002

**Comment by robhyrk** [comment]
Missing info regarding whether the transactions are buy or sell events. [Issue opened on subsquid](https://github.com/zeitgeistpm/zeitgeist-subsquid/issues/340)
