### ISSUE TITLE
Mobile menu missing items

### ISSUE THREAD

**Issue by robhyrk** [zeitgeistpm/ui#663]
![Screen Shot 2023-02-03 at 5 50 52 PM](https://user-images.githubusercontent.com/14626415/216726254-2066a6c9-d0e9-4135-b076-cd5933fe49c2.png)

- may also require some design changes

**Comment by lsaether** [comment]
@mk26071980  Please add figma link

**Comment by mk26071980** [comment]
<img width="325" alt="image" src="https://user-images.githubusercontent.com/80706590/220319583-7a00a064-fc3e-4049-8863-35bab6b42451.png">

https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?node-id=3803%3A22647&t=JPYRp7LYT6IfYn2N-1
