### ISSUE TITLE
Scalar date market page broken after being reported

### ISSUE THREAD

**Issue by TvrtkoM** [zeitgeistpm/ui#667]
I used minimum value input auto-filled for report value and now the market page is broken giving Application Error.
Reported scalar date market, details page is broken https://staging.zeitgeist.pm/markets/560

**Comment by TvrtkoM** [comment]
#659

**Comment by Robiquet** [comment]
Error in console:
<img width="554" alt="image" src="https://user-images.githubusercontent.com/4950844/216976193-bffcc6c6-255f-48ee-906d-921e723a6045.png">
