### ISSUE TITLE
Support proxy calls in app

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#670]
It would be great to be able to use proxies. To elaborate, our runtime allows users to set a _proxy_ for an account which allows the proxy to sign transactions for that account (the _real_ account). Haven't thought this through, but maybe we could let the user specify the real account in the **Account** modal if they want to us their account as proxy? The combobox used for this could be labeled _Use as proxy for_.

Beyond that, this is just a matter of passing the transaction `tx` that you would normally be signing directly as argument to `proxy_tx = api.tx.proxy.proxy(real, "any", tx)` and then signing `proxy_tx` with the proxy account. The second argument is the type of proxy. I think we can let that default to `"any"` for now.

One use-case for this is to allow the Advisory Committee to create markets and provide liquidity using proxy access to a joint account.

**Comment by Robiquet** [comment]
Once we've centralised transaction handling in the app this shouldn't be too hard to do. Though I'm unsure if the app level is the right place to provide this or if it should be done at the wallet level

**Comment by maltekliemann** [comment]
By "wallet level" you mean polkadot-js should offer this feature, or a you referring to something that we can actually implement?

**Comment by Robiquet** [comment]
Yeah I'm wondering if it something that wallets should implement, not sure if it's possible though

**Comment by maltekliemann** [comment]
I agree that this would be the ideal solution. In fact, I'm not a fan at all of doing a homebrew solution for this, but I don't understand polkadot-js sufficiently to see what the hold up is.

**Comment by lsaether** [comment]
@mk26071980 We may not want to do this afterall- connect with team before starting work.
