### ISSUE TITLE
Settings Modal

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/ui#716]

**Comment by lsaether** [comment]
@mk26071980 Can you add the link to design?

**Comment by mk26071980** [comment]
<img width="927" alt="image" src="https://github.com/zeitgeistpm/ui/assets/80706590/e89f6e0f-4eb0-4c87-b2ad-3be5315fa801">
https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?type=design&node-id=3803%3A22647&t=Uhg44Kaxv6INLCnn-1

**Comment by mk26071980** [comment]
![Image](https://github.com/zeitgeistpm/ui/assets/80706590/b4e07a84-b11b-4396-9e5c-e2efdf3a7828)
