### ISSUE TITLE
Add _End of day_ shortcut for setting the market period's end

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#724]
Would be really useful to not always have to manually set the market end to 11:59 PM. How do you feel about adding a button (or some other thingemajig) which sets the end of the market to the end of day.

Extending this a little bit, _End of week/month/quarter/year_ also sounds interesting, but may not be a net plus (end of X can be easily done by selecting the last day of X and then using the _End of day_ button).

**Comment by lsaether** [comment]
Related to the create market page @mk26071980

**Comment by lsaether** [comment]
Meanwhile we will set the default time to 11:59

**Comment by mk26071980** [comment]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/80706590/220603410-b23813d9-0b4b-46d4-86b2-5416ecd98f38.png">
https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?node-id=4082%3A25035&t=EKM80QDlLKSgCDGu-1

**Comment by maltekliemann** [comment]
@mk26071980 Thank you! I think the most common situations we should cover are:

- Market ends at the end of a month (so not necessarily _this_ month, but any future month). Would be cool if we could select a month from a calendar and then have the market end at the end of the selected month.
- Market ends at the end of a quarter or year. But I think that's covered by the point above (people just select March, June, September or December).
- Market ends at the end of a particular day (so no necessarily _today_, but some future day). Same as above, would be cool if we could select that from the calendar.

Your suggestion only seems to cover _today_, etc., if I'm reading this right.

Another question is what timezone we're talking about here. @lsaether What's the word on letting the user select a time zone or making UTC the "default" time zone of the app?

**Comment by mk26071980** [comment]
But this is how it works. You have presets for this day, this week, this month, and this year. The rest you pick on a calendar

**Comment by maltekliemann** [comment]
> But this is how it works. You have presets for this day, this week, this month, and this year. The rest you pick on a calendar

Okay, I may have misunderstood. Just to clarify: Suppose it's Feb. 24 and I pick Mar. 25 from the calendar and then press _end of day_, then the market should end at the end of Mar. 25. So the _end of day_ button is a shortcut for selecting the end of the day for _any_ day. Is that how it works right now?

**Comment by mk26071980** [comment]
No, end of the day should refer to the current day. On a calendar you pick the specific day and the time you need. 

Cal widget looks like this 
<img width="409" alt="image" src="https://user-images.githubusercontent.com/80706590/221167191-f0bfa780-539e-490d-a5f9-e2ae062a3ca9.png">

**Comment by mk26071980** [comment]
Instead of End of Day we can use Today maybe?

**Comment by maltekliemann** [comment]
> No, end of the day should refer to the current day.

Depends on what you mean by "should". The situation that market creators are in right now is that usually markets end at the end of a certain day. For example, most of the markets we've created in the last couple of weeks either end at the end of this quarter (i.e. Mar. 31, 11:59 PM) or at the end of Mar. 24 (with a grace period of 7 days). So what I'm proposing is to give users the option to quickly set the end of the market to the end of _any_ day.

On the other hand, a button which sets the market's end to the end of today will probably not be used because a market that only runs for a couple of hours will not receive enough attention.

**Comment by mk26071980** [comment]
Ok, but what's wrong with setting up the any end day and time using calendar? How's that confusing?

**Comment by maltekliemann** [comment]
Oh, no, that's fine. I'm just referring to this:

> On a calendar you pick the specific day and the time you need.

The whole idea of this feature is that I don't want to set the time manually everytime I want to end a market at the end of the selected day (UTC). Using the calendar to do this would be perfect, not opposed to that at all.

**Comment by Robiquet** [comment]
Changed default time to 23:59
