### ISSUE TITLE
When a user enters a market that has a promotion campaign there should be a popup with the rules

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/ui#750]
A modal popup should display the rules for a promotional trading campaign when a market has one active.

**Comment by mk26071980** [comment]
<img width="654" alt="image" src="https://user-images.githubusercontent.com/80706590/221894284-d4e2e66a-9b97-4663-8b7a-e35889785d40.png">
https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?node-id=3803%3A22647&t=30U3x0P2jOL33H8b-1

**Comment by lsaether** [comment]
![image](https://user-images.githubusercontent.com/25539605/221920909-42c45edd-b0be-4f80-9edd-595c74256d2f.png)

**Comment by Robiquet** [comment]
I think we should look into using a CMS to populate this stuff to reduce dev overhead

**Comment by lsaether** [comment]
@Robiquet https://supabase.com/database ?

**Comment by Robiquet** [comment]
@lsaether I was considering https://www.sanity.io . Does supabase have a frontend that the marketing team could add content to?

**Comment by lsaether** [comment]
I believe it does, but it's pretty utilitarian and not so pretty. On that note, do you think we could use Notion for this? Since it's a tool everyone is already familiar with and we don't have to set anything up.
