### ISSUE TITLE
Navbar has too much horizontal padding on large screens

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/ui#772]
On large screens the navbar is misaligned with the buttons

![image](https://user-images.githubusercontent.com/25539605/222431498-e9a82588-e362-4666-8ee4-aa9bdd5c0ff1.png)

**Comment by robhyrk** [comment]
Should the navbar be the full width of the screen or should should the side menu follow alignment of the navbar?

option 1:
![Screenshot 2023-03-03 at 3 50 20 PM](https://user-images.githubusercontent.com/14626415/222826808-38b4e44b-af8b-4c6a-9049-62fd5a99a756.png)

option 2:
![Screenshot 2023-03-03 at 3 51 39 PM](https://user-images.githubusercontent.com/14626415/222826909-cf13d2b7-c599-4f88-8bf7-3b4d6b5ece78.png)

**Comment by lsaether** [comment]
Option 2
