### ISSUE TITLE
Market list errors some times

### ISSUE THREAD

**Issue by yornaath** [zeitgeistpm/ui#802]
The market list on `https://test.staging.zeitgeist.pm/markets` sometimes errors out when the filter changes, it seems to be random to me, sometimes when removing the active status filter or the liquidity only filter.

I couldn't reproduce in staging.zeitgeist or app.zeitgeist so might be related to some new gql schema or type changes.

**Comment by lsaether** [comment]
Possibly related to Tvrtko's reported issues
