### ISSUE TITLE
"Create" page spacing and alignment on mobile

### ISSUE THREAD

**Issue by robhyrk** [zeitgeistpm/ui#810]
![Screenshot 2023-03-06 at 12 48 36 PM](https://user-images.githubusercontent.com/14626415/223190438-2f5d4317-214f-4eef-b169-4d84930909e8.png)

![Screenshot 2023-03-06 at 12 48 42 PM](https://user-images.githubusercontent.com/14626415/223190459-f10c5de8-39a1-476a-a397-c6f8f54d1836.png)

**Comment by lsaether** [comment]
We will revamp the create market page during the next sprint.
