### ISSUE TITLE
Remove MarketStore usage from Market page and use react-query

### ISSUE THREAD

**Issue by TvrtkoM** [zeitgeistpm/ui#815]
For example https://test.staging.zeitgeist.pm/markets/569

- the skeletons are not being replaced with actual data
![image](https://user-images.githubusercontent.com/551965/223384561-85a6e9c8-2570-46bb-8e4a-b9162c4dc8bc.png)

- after a while errors shows up in the console
```
TypeError: Failed to fetch
///  ...
TypeError: Cannot destructure property '__meta' of 'decodedMetadata' as it is undefined.
```

same for this https://test.staging.zeitgeist.pm/markets/566

**Comment by lsaether** [comment]
Related to #820

**Comment by yornaath** [comment]
@saboonikhil This error originates in the sdkv1 since the __meta property isnt available on older market metadata.

**Comment by saboonikhil** [comment]
> @saboonikhil This error originates in the sdkv1 since the __meta property isnt available on older market metadata.

`v1.0.4` should have the https://github.com/zeitgeistpm/tools/pull/249 changes.

**Comment by lsaether** [comment]
- We need to load all the data from Subsquid instead of sending IPFS requests to load metadata.
- Involves refactoring mobx stores to react-query.

**Comment by lsaether** [comment]
Create a hook for the market prize pool, and possibly more
