### ISSUE TITLE
Set up jest for component testing

### ISSUE THREAD

**Issue by TvrtkoM** [zeitgeistpm/ui#836]
Write a couple of tests for some components of small to medium complexity, and come up with a plan for refactoring other components so they're more easy to test

**Comment by TvrtkoM** [comment]
Investigated so far:

Jest (since we already use it for unit testing)
- runs in nodejs
- node related errors when running e.g. `ReferneceError: TextDecoder is not defined`
- couldn't get it to work
- configuration feels like hit and miss

Main issues is in uint8arrays dependency that seem to originate from polkadotjs dependencies / sdk and it is related to `ipfs-http-client`
```
```
.../.../zeitgeist/ui/node_modules/multihashes/node_modules/uint8arrays/esm/src/to-string.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import bases from './util/bases.js';
```

Cypress
- runs in browser so there were no nodejs related issues
- configuration was running smoothly
- disadvantage is having to deal with cypress promises instead of async / await code, but it seems there are some libs that can help with that
- should investigate usage of cypress with visual regression tools like percy (https://percy.io/) or happo (https://happo.io/)

**Comment by lsaether** [comment]
Look into replacing `ipfs-http-client` with something else / our own code since it continues to give us issues.
