### ISSUE TITLE
Get ZTG from DEX 

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#837]
A continuation from this modal
<img width="478" alt="image" src="https://user-images.githubusercontent.com/4950844/224103483-e540f01b-0ebb-4d84-8e73-0b8301b582d3.png">

**Comment by JamesPrestonZA** [comment]
Apologies for the delay on this. Got caught up in some other comms priorities. This blog post will be ready by Wednesday 24 May.

**Comment by JamesPrestonZA** [comment]
Hi all. The blog post of the tutorial is ready here:
(https://blog.zeitgeist.pm/how-to-buy-ztg-on-hydradxs-omnipool/)

(Sorry, video was ready, but just needed final approval).
