### ISSUE TITLE
Mobile wallet connection

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#860]
Currently looks like this, maybe this is ok but seems a bit weird
<img width="359" alt="image" src="https://user-images.githubusercontent.com/4950844/225368375-1ce29d77-0eec-4883-9b3d-cecc60092951.png">

**Comment by lsaether** [comment]
@mk26071980 Will look into the design

**Comment by mk26071980** [comment]
https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?node-id=3622%3A28814&t=s8kozfhxbUgYD3Gf-1

<img width="829" alt="image" src="https://user-images.githubusercontent.com/80706590/229486594-82d0776d-2e2f-407b-9428-0c6a63c6a80c.png">
 I also think we might slide the modals from the side on the mobile and tablet. Maybe not at this moment, but eventually

**Comment by mk26071980** [comment]
Needs copy from J.
