### ISSUE TITLE
Show disputed/reported/resolved outcome in table

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#862]
![image](https://user-images.githubusercontent.com/4950844/225379964-6828c76b-91d9-4458-958d-087f6d7a1a3a.png)

**Comment by mk26071980** [comment]
https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?node-id=3970%3A22391&t=yPBjqSIZAbyxYj51-1

**Comment by robhyrk** [comment]
holding off until completion of #815

**Comment by Robiquet** [comment]
@mk26071980 how should this work for scalar markets?

**Comment by mk26071980** [comment]
What do you mean? Screeshot is a scalar market

**Comment by Robiquet** [comment]
> What do you mean? Screeshot is a scalar market

Scalar markets resolve to a specific number, not long or short
