### ISSUE TITLE
Withdrawing liquidity from resolved categorical markets fails

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#889]
The chain actually removes the losing assets from the pool. For example, note that this pool only has one categorical outcome left:

<img width="1920" alt="Screenshot 2023-03-20 at 17 07 46" src="https://user-images.githubusercontent.com/49552287/226400360-fabebf38-9eb2-4937-ae61-a78aff085757.png">

The frontend seems to assume that this is not the case and therefore misconfigures the `minAssetsOut` vector parameter (it's too long).

This doesn't pertain to scalar markets because other outcomes are considered to be winners (even if the reported outcome lies outside of the range of the market).

**Comment by TvrtkoM** [comment]
Currently we're iterating over `pool.weights` to calculate `minAssetOut` vector that still has all the outcomes in it and it is all done by using data from subsquid / graphql

e.g. market on battery station with id 594 is now resolved and pool id 226 when queried on https://processor.bsr.zeitgeist.pm/graphql as follows

```
query MyQuery {
  pools(where: {poolId_eq: 226}) {
    assets {
      assetId
      amountInPool
    }
    weights {
      assetId
      len
    }
  }
}
```

still contains both losing and wining assets.
