### ISSUE TITLE
Chaos-Slider bar & manual input on trades

### ISSUE THREAD

**Issue by degenofdotsama** [zeitgeistpm/ui#895]
When using the slider bar to vote & then trying to refine it and maybe shave off a decimal or a couple ZTG the manual input just kills the output of the trade.  

lower amounts don't work at all.  You have to activate the slider for anything under 39 ztg

<img width="845" alt="Screenshot 2023-03-20 at 14 20 18" src="https://user-images.githubusercontent.com/88508554/226444121-e51cffd9-fd52-4e87-8edc-f579da71375e.png">
<img width="845" alt="Screenshot 2023-03-20 at 14 20 34" src="https://user-images.githubusercontent.com/88508554/226444131-ecf18d28-5fed-4e25-937b-634783bb62e0.png">

https://user-images.githubusercontent.com/88508554/226442881-4df3f589-e50a-4c2e-ac37-be3eb6e48546.mov

**Comment by lsaether** [comment]
@TvrtkoM Could you please take a look at this?

**Comment by TvrtkoM** [comment]
Fixed on PR #841
