### ISSUE TITLE
change slider animation

### ISSUE THREAD

**Issue by robhyrk** [zeitgeistpm/ui#908]
change to slider transition left-to-right

**Comment by mk26071980** [comment]
I was thinking about smth like this https://codepen.io/takayuki-kojima/pen/bONKxg
with [4S](transition: opacity 4s ease-in-out;)

**Comment by Robiquet** [comment]
Yeah that's cool, I think this is kind of what we're doing though the thing we're missing is preloading the 2nd page asset and display the 1st over the top of it as it fades out. At the moment we're kind of fading the same way but just to a white background
