### ISSUE TITLE
It is confusing that no values show as %. We should always show the yes %

### ISSUE THREAD

**Issue by Nathanpmyoung** [zeitgeistpm/ui#913]
<img width="398" alt="image" src="https://user-images.githubusercontent.com/20482100/227254244-73d7d52a-dacb-4da2-9a4d-3fd7fc1b9119.png">

Reading this market, it looks like this outcome is very likely to happen (82%) but that's not the case. It's 18%.

I suggest we should always show the yes %.

**Comment by mk26071980** [comment]
Actually, according to the market No is 82% to happen. The card shows the most probable outcome.

**Comment by Nathanpmyoung** [comment]
But %s are intrinsically positive. 

Will the SEC confirm that Dot is not a security in Q1? 82%

What does this 82% suggest. It suggests yes. This is what the bar looks like. Hence why all other sites use this.

<img width="847" alt="image" src="https://user-images.githubusercontent.com/20482100/227787057-c103a61a-18d8-4c5a-9d13-29a424696fe1.png">

<img width="1460" alt="image" src="https://user-images.githubusercontent.com/20482100/227787097-2c153e8e-3138-4afb-b1cc-5475c6741de8.png">

**Comment by mk26071980** [comment]
Agreed on Yes % as a default outcome for Yes/No markets
