### ISSUE TITLE
I want to see whether I have made profit or loss on a market

### ISSUE THREAD

**Issue by Nathanpmyoung** [zeitgeistpm/ui#915]
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/20482100/227256672-5c56ea0d-7557-4320-a15a-3a56bde18d4a.png">

Compare this to manifold.markets 

<img width="807" alt="image" src="https://user-images.githubusercontent.com/20482100/227256872-225b5db7-c0b1-4065-afe8-7a9aae6e17a1.png">

When folded, it has current value and profit/loss

when opened it has money spent, current expected value and profit.

**Comment by mk26071980** [comment]
Yeah, showing profit/loss data is being worked on. At the moment the idea is to show an additional column to the table, as far as I remember. But we might think of other solutions. @Robiquet

**Comment by Nathanpmyoung** [comment]
A table seems good. This is a table with dropwowns for each item: https://manifold.markets/NathanpmYoung?tab=portfolio

**Comment by lsaether** [comment]
@saboonikhil

**Comment by saboonikhil** [comment]
Resolution of https://github.com/zeitgeistpm/zeitgeist-subsquid/issues/340 should uncover meaningful informations including this.

**Comment by robhyrk** [comment]
@mk26071980 do you have a vision how to expand on this concept? Right now we've added a few extra columns with the values on the portfolio page. 

Wondering if it's worth expanding on this or leaving as is?

**Comment by Robiquet** [comment]
Added realised/unrealised profit and loss
