### ISSUE TITLE
Need to add Chevron Down Icon to the Account Component

### ISSUE THREAD

**Issue by mk26071980** [zeitgeistpm/ui#919]
Need to add Chevron Down Icon to the Account Component, so it indicates the dropdown

**Comment by robhyrk** [comment]
Are there deisgns available for this?

**Comment by mk26071980** [comment]
Updated components 
<img width="721" alt="image" src="https://user-images.githubusercontent.com/80706590/232756864-7700e400-e64f-4db7-96bf-fffd64d3c8dc.png">
https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?node-id=1327%3A8329&t=V9GiGyfuf4aBvLkF-1
