### ISSUE TITLE
Filter component for tablets and Mobiles

### ISSUE THREAD

**Issue by mk26071980** [zeitgeistpm/ui#921]
https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?node-id=3970%3A22390&t=Fa5B8Nj2Z1dvb0O0-1

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/80706590/227474337-4ec358d9-2a50-4235-b8fa-d4848329d837.png">

**Comment by lsaether** [comment]
@TvrtkoM What's the status on this?

**Comment by lsaether** [comment]
Ok, I see it's marked "Done". Re-open if it's not done.
