### ISSUE TITLE
Add market history modal

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#960]
I can't see who made the dispute, and the time bar show 100%.

<img width="1920" alt="Screenshot 2023-04-03 at 11 55 41" src="https://user-images.githubusercontent.com/49552287/229476672-2b96fdd0-8f01-4bf4-b318-5e031d11f89d.png">

**Comment by robhyrk** [comment]
Do we need a design for this?

To keep it simple we can probably just add text: "Market outcome: Disputed by `user`"

**Comment by maltekliemann** [comment]
I think the usual subscan/etc. links for the user (maybe plus avatar?) and the exact time/block of the dispute are perfectly fine.

**Comment by Robiquet** [comment]
Let's wait for a design, I think @mk26071980 is working on something related and there are a few other things to consider

**Comment by mk26071980** [comment]
As discussed with Tom 

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/80706590/231430321-c646e0c9-c6b1-4252-b885-3312cc67a365.png">
<img width="962" alt="image" src="https://user-images.githubusercontent.com/80706590/231430383-e3699c1c-3d7d-45f4-9a49-d9b0fa569572.png">

**Comment by Robiquet** [comment]
> As discussed with Tom
> 
> <img alt="image" width="1003" src="https://user-images.githubusercontent.com/80706590/231430321-c646e0c9-c6b1-4252-b885-3312cc67a365.png">
> 
> <img alt="image" width="962" src="https://user-images.githubusercontent.com/80706590/231430383-e3699c1c-3d7d-45f4-9a49-d9b0fa569572.png">

@maltekliemann do you need dispute date too, or does this work for you?

**Comment by robhyrk** [comment]
There is missing dispute data for `SimpleDisputes` so exploring as to why that is. Will incorporate these features for `Authorized` disputes in the meantime.

**Comment by maltekliemann** [comment]
> There is missing dispute data for `SimpleDisputes` so exploring as to why that is. Will incorporate these features for `Authorized` disputes in the meantime.

Yo, `simple-disputes` is deprecated at this point. No need to look into this further, I think.

Another idea for the design: How about a complete "market history"? Something like:

> - 2023-02-03T16:12Z (block 1234567) Market opened
> - 2023-03-31T23:59Z (block 1255555) Market closed
>  - 2023-04-01T00:12Z (block 1255556) oracle {account1} reported {outcome1}
>  - 2023-04-01T00:24Z (block 1255557) {account2} disputed and suggested {outcome2}
> - 2023-04-01T00:36Z (block 1255558) Authority reported {outcome3}
> - 2023-04-02T00:36Z (block xxxxx) Market resolved to {outcome3}

**Comment by mk26071980** [comment]
Yep, we have a new layout. I also added a link that pops up a Market History modal 
https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?node-id=3970%3A22391&t=V9GiGyfuf4aBvLkF-1

**Comment by Robiquet** [comment]
I like the detailed summary. Though don't think we need so much info here now if it's in the modal, it takes up quite a lot of space 
<img width="353" alt="image" src="https://user-images.githubusercontent.com/4950844/232755789-4617b983-49af-4c45-bcf0-75f799767756.png">

May something could be added to the market timeline component?

**Comment by Robiquet** [comment]
Users might want to see history when there isn't a dispute so we should have a way to display that

**Comment by mk26071980** [comment]
Link See History should be next to winning outcome, reported outcome, disputed outcome. And the modal contains info on all the market history, not only disputes.

**Comment by Robiquet** [comment]
How should it look for proposed and active markets?

**Comment by mk26071980** [comment]
What kind of history related to outcomes should be there?

Вт, 18 апр. 2023 г. в 14:24, Tom Robiquet ***@***.***>:

**Comment by Robiquet** [comment]
The key events in the early market stages would be: market created, market approved, pool deployed, market started. Though not sure how important these are, maybe @maltekliemann has an opinion

**Comment by Robiquet** [comment]
I'm not sure about outcome specific stuff, just wondering how we should display the 'See history' button in that case

**Comment by mk26071980** [comment]
If we display full history info on the market, it should be done differently. Personally, I'm not sure if additional info (not related to resolving the market) has value for the user.

**Comment by mk26071980** [comment]
https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?node-id=3970%3A22391&t=39sakXJxIhW0ruJr-1

**Comment by maltekliemann** [comment]
I think displaying when the market was created, approved (if applicable), closed, reported, disputed and resolved would be a good idea.

> https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?node-id=3970%3A22391&t=39sakXJxIhW0ruJr-1

Looks cool. I would love if we could replace the numeration (1., 2., etc.) of each item with a symbol which represent the different states of the market. Not sure which symbol, though. A gavel for disputes makes sense. Maybe a bell for opening and closing? IDK...

**Comment by mk26071980** [comment]
Sure. There's already design for this (see link) based on your structure
