### ISSUE TITLE
Add modal to confirm dispute

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#964]
After clicking the dispute button, a modal should be displayed showing the cost of the transaction and explaining the consequences of a dispute

**Comment by Robiquet** [comment]
Repurposing the Scalar dispute box for now
<img width="417" alt="image" src="https://user-images.githubusercontent.com/4950844/230406709-904b56e1-fa83-481e-8472-3152af9bbef9.png">

**Comment by mk26071980** [comment]
<img width="597" alt="image" src="https://user-images.githubusercontent.com/80706590/232438822-767d21b6-655a-4ab6-a59a-923ac6dcdd91.png">
https://www.figma.com/file/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?node-id=3803%3A22647&t=s4GlsYkqqvPwIlcr-1

**Comment by lsaether** [comment]
@Robiquet Was this added?
