### ISSUE TITLE
Refactor notifications from imperative callback style to declarative rendering.

### ISSUE THREAD

**Issue by yornaath** [zeitgeistpm/ui#996]
Declarative approach vs imperative approach.

```ts
const Declarative = () => {
  const { send, isError, isSuccess } = useExtrinsic(...);

  return (
    <div>
      {isSuccess ? (
        <Notification message="Transaction Success." type="success" />
      ) : 
      isError ? (
        <Notification message="Transaction Failed." type="error" />
      ) : null}
    </div>
  );
};

const Imperative = () => {
  const { send, isError, isSuccess } = useExtrinsic({}, {
    onSuccess: () => {
      notificationStore.pushNotification("Exited pool", {
        type: "Success",
      });
    }
  });

  return (
    <div>
      ...
    </div>
  );
};
```

Personally I like the declarative approach better. What do you guys think? @TvrtkoM @Robiquet @lsaether

**Comment by robhyrk** [comment]
Declarative is easier to read imo

**Comment by Robiquet** [comment]
If we use declarative, how does `useExtrinsic` know to override default behaviour?

**Comment by yornaath** [comment]
> If we use declarative, how does `useExtrinsic` know to override default behaviour?

Yeah I was thinking about this immediately after posting it. Not sure tbh so for now lets just keep the imperative approach.
